
#ifndef SOLVERMPCC_CASADI_H
#define SOLVERMPCC_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int solverMPCC_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_objective_1_sparsity_out(casadi_int i);
int solverMPCC_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_dynamics_1_sparsity_out(casadi_int i);
int solverMPCC_dynamics_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_inequalities_1_sparsity_out(casadi_int i);
int solverMPCC_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_objective_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_objective_2_sparsity_out(casadi_int i);
int solverMPCC_objective_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_dynamics_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_dynamics_2_sparsity_out(casadi_int i);
int solverMPCC_dynamics_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_inequalities_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_inequalities_2_sparsity_out(casadi_int i);
int solverMPCC_inequalities_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_objective_35(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_objective_35_sparsity_out(casadi_int i);
int solverMPCC_objective_35_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_dynamics_35(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_dynamics_35_sparsity_out(casadi_int i);
int solverMPCC_dynamics_35_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverMPCC_objective_36(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverMPCC_objective_36_sparsity_out(casadi_int i);
int solverMPCC_objective_36_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
