/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) car_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[19] = 
  {4, 4, 0, 3, 6, 9, 12, 0,
  1, 3, 0, 1, 3, 0, 1, 3,
  0, 1, 3};
static const casadi_int casadi_s1[7] = {4, 2, 0, 1, 2, 2, 3};
static const casadi_int casadi_s2[9] = 
  {2, 4, 0, 0, 0, 1, 2, 0,
  1};
static const casadi_int casadi_s3[11] = 
  {4, 2, 0, 3, 6, 0, 1, 3,
  0, 1, 3};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {4, 4, 1};
static const casadi_int casadi_s6[3] = {4, 2, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {0, 0, 1};

static const casadi_real casadi_zeros[16] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* car_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, *w07=w+7, w12, w13, *w15=w+41;
  casadi_real w16, *w17=w+45, *w18=w+48, *w19=w+51, *w20=w+54, *w21=w+66, *w22=w+68, *w23=w+70, *w24=w+72, *w25=w+80, *w26=w+88;
  const casadi_real *cs, *wr07, *wr08, *wr09, *wr10, *wr11, *wr25;
  /* #0: @0 = input[0][2] */
  w00 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = cos(@1) */
  w02 = cos( w01 );
  /* #3: @3 = (@0*@2) */
  w03  = (w00*w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @1 = sin(@1) */
  w01 = sin( w01 );
  /* #6: @3 = (@0*@1) */
  w03  = (w00*w01);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @3 = input[3][0] */
  w03 = arg[3] ? arg[3][0] : 0;
  /* #9: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #10: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #11: @4 = tan(@3) */
  w04 = tan( w03 );
  /* #12: @5 = (@0*@4) */
  w05  = (w00*w04);
  /* #13: @6 = 2.5 */
  w06 = 2.5000000000000000e+00;
  /* #14: @5 = (@5/@6) */
  w05 /= w06;
  /* #15: output[0][3] = @5 */
  if (res[0]) res[0][3] = w05;
  /* #16: @7 = input[1][0] */
  wr07 = arg[1] ? arg[1] : casadi_zeros;
  /* #17: {@8, @9, @10, @11} = horzsplit(@7) */
  wr08 = wr07;
  wr09 = wr07+4;
  wr10 = wr07+8;
  wr11 = wr07+12;
  /* #18: {NULL, NULL, @5, @6} = vertsplit(@8) */
  w05 = wr08[2];
  w06 = wr08[3];
  /* #19: @12 = (@2*@5) */
  w12  = (w02*w05);
  /* #20: @13 = (@1*@6) */
  w13  = (w01*w06);
  /* #21: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #22: @12 = (@12-@13) */
  w12 -= w13;
  /* #23: @13 = (@1*@5) */
  w13  = (w01*w05);
  /* #24: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #25: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #26: @13 = (@13+@6) */
  w13 += w06;
  /* #27: @14 = 00 */
  /* #28: @6 = 0.4 */
  w06 = 4.0000000000000002e-01;
  /* #29: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #30: @5 = (@6*@5) */
  w05  = (w06*w05);
  /* #31: @15 = vertcat(@12, @13, @14, @5) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w05;
  /* #32: {NULL, NULL, @12, @13} = vertsplit(@9) */
  w12 = wr09[2];
  w13 = wr09[3];
  /* #33: @5 = (@2*@12) */
  w05  = (w02*w12);
  /* #34: @16 = (@1*@13) */
  w16  = (w01*w13);
  /* #35: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #36: @5 = (@5-@16) */
  w05 -= w16;
  /* #37: @16 = (@1*@12) */
  w16  = (w01*w12);
  /* #38: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #39: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #40: @16 = (@16+@13) */
  w16 += w13;
  /* #41: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #42: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #43: @17 = vertcat(@5, @16, @14, @12) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w16;
  *rr++ = w12;
  /* #44: {NULL, NULL, @5, @16} = vertsplit(@10) */
  w05 = wr10[2];
  w16 = wr10[3];
  /* #45: @12 = (@2*@5) */
  w12  = (w02*w05);
  /* #46: @13 = (@1*@16) */
  w13  = (w01*w16);
  /* #47: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #48: @12 = (@12-@13) */
  w12 -= w13;
  /* #49: @13 = (@1*@5) */
  w13  = (w01*w05);
  /* #50: @16 = (@2*@16) */
  w16  = (w02*w16);
  /* #51: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #52: @13 = (@13+@16) */
  w13 += w16;
  /* #53: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #54: @5 = (@6*@5) */
  w05  = (w06*w05);
  /* #55: @18 = vertcat(@12, @13, @14, @5) */
  rr=w18;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w05;
  /* #56: {NULL, NULL, @12, @13} = vertsplit(@11) */
  w12 = wr11[2];
  w13 = wr11[3];
  /* #57: @5 = (@2*@12) */
  w05  = (w02*w12);
  /* #58: @16 = (@1*@13) */
  w16  = (w01*w13);
  /* #59: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #60: @5 = (@5-@16) */
  w05 -= w16;
  /* #61: @16 = (@1*@12) */
  w16  = (w01*w12);
  /* #62: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #63: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #64: @16 = (@16+@13) */
  w16 += w13;
  /* #65: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #66: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #67: @19 = vertcat(@5, @16, @14, @12) */
  rr=w19;
  *rr++ = w05;
  *rr++ = w16;
  *rr++ = w12;
  /* #68: @20 = horzcat(@15, @17, @18, @19) */
  rr=w20;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #69: @7 = dense(@20) */
  casadi_densify(w20, casadi_s0, w07, 0);
  /* #70: output[1][0] = @7 */
  casadi_copy(w07, 16, res[1]);
  /* #71: @21 = zeros(2x4,2nz) */
  casadi_clear(w21, 2);
  /* #72: @22 = ones(2x1) */
  casadi_fill(w22, 2, 1.);
  /* #73: {@5, @16} = vertsplit(@22) */
  w05 = w22[0];
  w16 = w22[1];
  /* #74: @3 = cos(@3) */
  w03 = cos( w03 );
  /* #75: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #76: @16 = (@16/@3) */
  w16 /= w03;
  /* #77: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #78: @16 = (@6*@16) */
  w16  = (w06*w16);
  /* #79: @22 = vertcat(@14, @14, @5, @16) */
  rr=w22;
  *rr++ = w05;
  *rr++ = w16;
  /* #80: @23 = @22[:2] */
  for (rr=w23, cs=w22+0; cs!=w22+2; cs+=1) *rr++ = *cs;
  /* #81: (@21[:2] = @23) */
  for (rr=w21+0, cs=w23; rr!=w21+2; rr+=1) *rr = *cs++;
  /* #82: @23 = @21' */
  casadi_trans(w21,casadi_s2, w23, casadi_s1, iw);
  /* #83: @24 = dense(@23) */
  casadi_densify(w23, casadi_s1, w24, 0);
  /* #84: @25 = input[2][0] */
  wr25 = arg[2] ? arg[2] : casadi_zeros;
  /* #85: {@11, @10} = horzsplit(@25) */
  wr11 = wr25;
  wr10 = wr25+4;
  /* #86: {NULL, NULL, @5, @16} = vertsplit(@11) */
  w05 = wr11[2];
  w16 = wr11[3];
  /* #87: @3 = (@2*@5) */
  w03  = (w02*w05);
  /* #88: @12 = (@1*@16) */
  w12  = (w01*w16);
  /* #89: @12 = (@0*@12) */
  w12  = (w00*w12);
  /* #90: @3 = (@3-@12) */
  w03 -= w12;
  /* #91: @12 = (@1*@5) */
  w12  = (w01*w05);
  /* #92: @16 = (@2*@16) */
  w16  = (w02*w16);
  /* #93: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #94: @12 = (@12+@16) */
  w12 += w16;
  /* #95: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #96: @5 = (@6*@5) */
  w05  = (w06*w05);
  /* #97: @15 = vertcat(@3, @12, @14, @5) */
  rr=w15;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w05;
  /* #98: {NULL, NULL, @3, @12} = vertsplit(@10) */
  w03 = wr10[2];
  w12 = wr10[3];
  /* #99: @5 = (@2*@3) */
  w05  = (w02*w03);
  /* #100: @16 = (@1*@12) */
  w16  = (w01*w12);
  /* #101: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #102: @5 = (@5-@16) */
  w05 -= w16;
  /* #103: @1 = (@1*@3) */
  w01 *= w03;
  /* #104: @2 = (@2*@12) */
  w02 *= w12;
  /* #105: @0 = (@0*@2) */
  w00 *= w02;
  /* #106: @1 = (@1+@0) */
  w01 += w00;
  /* #107: @4 = (@4*@3) */
  w04 *= w03;
  /* #108: @6 = (@6*@4) */
  w06 *= w04;
  /* #109: @17 = vertcat(@5, @1, @14, @6) */
  rr=w17;
  *rr++ = w05;
  *rr++ = w01;
  *rr++ = w06;
  /* #110: @26 = horzcat(@15, @17) */
  rr=w26;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #111: @25 = dense(@26) */
  casadi_densify(w26, casadi_s3, w25, 0);
  /* #112: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<8; ++i) (*rr++) += (*cs++);
  /* #113: output[2][0] = @24 */
  casadi_copy(w24, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int car_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int car_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real car_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 94;
  return 0;
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 94*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
