/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Car_model_v1_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {8, 8, 1};
static const casadi_int casadi_s2[3] = {8, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {18, 1, 1};

/* Car_model_v1_expl_vde_forw:(i0[8],i1[8x8],i2[8x2],i3[2],i4[6],i5[18])->(o0[8],o1[8x8],o2[8x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][4] : 0;
  a01=sin(a01);
  a05=(a04*a01);
  a06=1.;
  a07=arg[0]? arg[0][1] : 0;
  a08=arg[4]? arg[4][0] : 0;
  a07=(a07*a08);
  a07=(a06-a07);
  a05=(a05/a07);
  a03=(a03-a05);
  if (res[0]!=0) res[0][0]=a03;
  a09=(a00*a01);
  a10=(a04*a02);
  a09=(a09+a10);
  if (res[0]!=0) res[0][1]=a09;
  a09=arg[0]? arg[0][5] : 0;
  a03=(a08*a03);
  a03=(a09-a03);
  if (res[0]!=0) res[0][2]=a03;
  a03=3.3333333333333331e-01;
  a10=75.;
  a11=arg[0]? arg[0][7] : 0;
  a11=(a10*a11);
  a12=4.5000000000000000e+00;
  a11=(a11-a12);
  a12=arg[5]? arg[5][6] : 0;
  a13=arg[5]? arg[5][1] : 0;
  a14=arg[5]? arg[5][0] : 0;
  a15=1.6200000000000001e-01;
  a16=(a15*a09);
  a17=(a04+a16);
  a17=(a17/a00);
  a18=atan(a17);
  a19=arg[0]? arg[0][6] : 0;
  a18=(a18-a19);
  a18=(a14*a18);
  a20=atan(a18);
  a20=(a13*a20);
  a21=sin(a20);
  a21=(a12*a21);
  a22=sin(a19);
  a23=(a21*a22);
  a11=(a11-a23);
  a23=3.;
  a24=(a23*a04);
  a25=(a24*a09);
  a11=(a11+a25);
  a11=(a03*a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=arg[5]? arg[5][7] : 0;
  a25=arg[5]? arg[5][4] : 0;
  a26=arg[5]? arg[5][3] : 0;
  a16=(a04-a16);
  a16=(a16/a00);
  a27=atan(a16);
  a27=(a26*a27);
  a28=atan(a27);
  a28=(a25*a28);
  a29=sin(a28);
  a29=(a11*a29);
  a19=cos(a19);
  a30=(a21*a19);
  a30=(a29+a30);
  a31=(a23*a00);
  a32=(a31*a09);
  a30=(a30-a32);
  a30=(a03*a30);
  if (res[0]!=0) res[0][4]=a30;
  a30=6.3506579281613575e+00;
  a32=(a15*a21);
  a33=(a32*a19);
  a29=(a15*a29);
  a33=(a33-a29);
  a33=(a30*a33);
  if (res[0]!=0) res[0][5]=a33;
  a33=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][6]=a33;
  a33=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][7]=a33;
  a33=arg[1]? arg[1][3] : 0;
  a29=(a02*a33);
  a34=arg[1]? arg[1][2] : 0;
  a35=(a01*a34);
  a36=(a00*a35);
  a29=(a29-a36);
  a36=arg[1]? arg[1][4] : 0;
  a37=(a01*a36);
  a34=(a02*a34);
  a38=(a04*a34);
  a37=(a37+a38);
  a37=(a37/a07);
  a05=(a05/a07);
  a38=arg[1]? arg[1][1] : 0;
  a38=(a08*a38);
  a38=(a05*a38);
  a37=(a37+a38);
  a29=(a29-a37);
  if (res[1]!=0) res[1][0]=a29;
  a37=(a01*a33);
  a34=(a00*a34);
  a37=(a37+a34);
  a34=(a02*a36);
  a35=(a04*a35);
  a34=(a34-a35);
  a37=(a37+a34);
  if (res[1]!=0) res[1][1]=a37;
  a37=arg[1]? arg[1][5] : 0;
  a29=(a08*a29);
  a29=(a37-a29);
  if (res[1]!=0) res[1][2]=a29;
  a29=arg[1]? arg[1][7] : 0;
  a29=(a10*a29);
  a20=cos(a20);
  a34=(a15*a37);
  a35=(a36+a34);
  a35=(a35/a00);
  a38=(a17/a00);
  a39=(a38*a33);
  a35=(a35-a39);
  a17=casadi_sq(a17);
  a17=(a06+a17);
  a35=(a35/a17);
  a39=arg[1]? arg[1][6] : 0;
  a35=(a35-a39);
  a35=(a14*a35);
  a18=casadi_sq(a18);
  a18=(a06+a18);
  a35=(a35/a18);
  a35=(a13*a35);
  a35=(a20*a35);
  a35=(a12*a35);
  a40=(a22*a35);
  a41=(a19*a39);
  a41=(a21*a41);
  a40=(a40+a41);
  a29=(a29-a40);
  a40=(a23*a36);
  a40=(a09*a40);
  a41=(a24*a37);
  a40=(a40+a41);
  a29=(a29+a40);
  a29=(a03*a29);
  if (res[1]!=0) res[1][3]=a29;
  a28=cos(a28);
  a36=(a36-a34);
  a36=(a36/a00);
  a34=(a16/a00);
  a29=(a34*a33);
  a36=(a36-a29);
  a16=casadi_sq(a16);
  a16=(a06+a16);
  a36=(a36/a16);
  a36=(a26*a36);
  a27=casadi_sq(a27);
  a27=(a06+a27);
  a36=(a36/a27);
  a36=(a25*a36);
  a36=(a28*a36);
  a36=(a11*a36);
  a29=(a19*a35);
  a39=(a22*a39);
  a40=(a21*a39);
  a29=(a29-a40);
  a29=(a36+a29);
  a33=(a23*a33);
  a33=(a09*a33);
  a37=(a31*a37);
  a33=(a33+a37);
  a29=(a29-a33);
  a29=(a03*a29);
  if (res[1]!=0) res[1][4]=a29;
  a35=(a15*a35);
  a35=(a19*a35);
  a39=(a32*a39);
  a35=(a35-a39);
  a36=(a15*a36);
  a35=(a35-a36);
  a35=(a30*a35);
  if (res[1]!=0) res[1][5]=a35;
  a35=0.;
  if (res[1]!=0) res[1][6]=a35;
  if (res[1]!=0) res[1][7]=a35;
  a36=arg[1]? arg[1][11] : 0;
  a39=(a02*a36);
  a29=arg[1]? arg[1][10] : 0;
  a33=(a01*a29);
  a37=(a00*a33);
  a39=(a39-a37);
  a37=arg[1]? arg[1][12] : 0;
  a40=(a01*a37);
  a29=(a02*a29);
  a41=(a04*a29);
  a40=(a40+a41);
  a40=(a40/a07);
  a41=arg[1]? arg[1][9] : 0;
  a41=(a08*a41);
  a41=(a05*a41);
  a40=(a40+a41);
  a39=(a39-a40);
  if (res[1]!=0) res[1][8]=a39;
  a40=(a01*a36);
  a29=(a00*a29);
  a40=(a40+a29);
  a29=(a02*a37);
  a33=(a04*a33);
  a29=(a29-a33);
  a40=(a40+a29);
  if (res[1]!=0) res[1][9]=a40;
  a40=arg[1]? arg[1][13] : 0;
  a39=(a08*a39);
  a39=(a40-a39);
  if (res[1]!=0) res[1][10]=a39;
  a39=arg[1]? arg[1][15] : 0;
  a39=(a10*a39);
  a29=(a15*a40);
  a33=(a37+a29);
  a33=(a33/a00);
  a41=(a38*a36);
  a33=(a33-a41);
  a33=(a33/a17);
  a41=arg[1]? arg[1][14] : 0;
  a33=(a33-a41);
  a33=(a14*a33);
  a33=(a33/a18);
  a33=(a13*a33);
  a33=(a20*a33);
  a33=(a12*a33);
  a42=(a22*a33);
  a43=(a19*a41);
  a43=(a21*a43);
  a42=(a42+a43);
  a39=(a39-a42);
  a42=(a23*a37);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a39=(a39+a42);
  a39=(a03*a39);
  if (res[1]!=0) res[1][11]=a39;
  a37=(a37-a29);
  a37=(a37/a00);
  a29=(a34*a36);
  a37=(a37-a29);
  a37=(a37/a16);
  a37=(a26*a37);
  a37=(a37/a27);
  a37=(a25*a37);
  a37=(a28*a37);
  a37=(a11*a37);
  a29=(a19*a33);
  a41=(a22*a41);
  a39=(a21*a41);
  a29=(a29-a39);
  a29=(a37+a29);
  a36=(a23*a36);
  a36=(a09*a36);
  a40=(a31*a40);
  a36=(a36+a40);
  a29=(a29-a36);
  a29=(a03*a29);
  if (res[1]!=0) res[1][12]=a29;
  a33=(a15*a33);
  a33=(a19*a33);
  a41=(a32*a41);
  a33=(a33-a41);
  a37=(a15*a37);
  a33=(a33-a37);
  a33=(a30*a33);
  if (res[1]!=0) res[1][13]=a33;
  if (res[1]!=0) res[1][14]=a35;
  if (res[1]!=0) res[1][15]=a35;
  a33=arg[1]? arg[1][19] : 0;
  a37=(a02*a33);
  a41=arg[1]? arg[1][18] : 0;
  a29=(a01*a41);
  a36=(a00*a29);
  a37=(a37-a36);
  a36=arg[1]? arg[1][20] : 0;
  a40=(a01*a36);
  a41=(a02*a41);
  a39=(a04*a41);
  a40=(a40+a39);
  a40=(a40/a07);
  a39=arg[1]? arg[1][17] : 0;
  a39=(a08*a39);
  a39=(a05*a39);
  a40=(a40+a39);
  a37=(a37-a40);
  if (res[1]!=0) res[1][16]=a37;
  a40=(a01*a33);
  a41=(a00*a41);
  a40=(a40+a41);
  a41=(a02*a36);
  a29=(a04*a29);
  a41=(a41-a29);
  a40=(a40+a41);
  if (res[1]!=0) res[1][17]=a40;
  a40=arg[1]? arg[1][21] : 0;
  a37=(a08*a37);
  a37=(a40-a37);
  if (res[1]!=0) res[1][18]=a37;
  a37=arg[1]? arg[1][23] : 0;
  a37=(a10*a37);
  a41=(a15*a40);
  a29=(a36+a41);
  a29=(a29/a00);
  a39=(a38*a33);
  a29=(a29-a39);
  a29=(a29/a17);
  a39=arg[1]? arg[1][22] : 0;
  a29=(a29-a39);
  a29=(a14*a29);
  a29=(a29/a18);
  a29=(a13*a29);
  a29=(a20*a29);
  a29=(a12*a29);
  a42=(a22*a29);
  a43=(a19*a39);
  a43=(a21*a43);
  a42=(a42+a43);
  a37=(a37-a42);
  a42=(a23*a36);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a37=(a37+a42);
  a37=(a03*a37);
  if (res[1]!=0) res[1][19]=a37;
  a36=(a36-a41);
  a36=(a36/a00);
  a41=(a34*a33);
  a36=(a36-a41);
  a36=(a36/a16);
  a36=(a26*a36);
  a36=(a36/a27);
  a36=(a25*a36);
  a36=(a28*a36);
  a36=(a11*a36);
  a41=(a19*a29);
  a39=(a22*a39);
  a37=(a21*a39);
  a41=(a41-a37);
  a41=(a36+a41);
  a33=(a23*a33);
  a33=(a09*a33);
  a40=(a31*a40);
  a33=(a33+a40);
  a41=(a41-a33);
  a41=(a03*a41);
  if (res[1]!=0) res[1][20]=a41;
  a29=(a15*a29);
  a29=(a19*a29);
  a39=(a32*a39);
  a29=(a29-a39);
  a36=(a15*a36);
  a29=(a29-a36);
  a29=(a30*a29);
  if (res[1]!=0) res[1][21]=a29;
  if (res[1]!=0) res[1][22]=a35;
  if (res[1]!=0) res[1][23]=a35;
  a29=arg[1]? arg[1][27] : 0;
  a36=(a02*a29);
  a39=arg[1]? arg[1][26] : 0;
  a41=(a01*a39);
  a33=(a00*a41);
  a36=(a36-a33);
  a33=arg[1]? arg[1][28] : 0;
  a40=(a01*a33);
  a39=(a02*a39);
  a37=(a04*a39);
  a40=(a40+a37);
  a40=(a40/a07);
  a37=arg[1]? arg[1][25] : 0;
  a37=(a08*a37);
  a37=(a05*a37);
  a40=(a40+a37);
  a36=(a36-a40);
  if (res[1]!=0) res[1][24]=a36;
  a40=(a01*a29);
  a39=(a00*a39);
  a40=(a40+a39);
  a39=(a02*a33);
  a41=(a04*a41);
  a39=(a39-a41);
  a40=(a40+a39);
  if (res[1]!=0) res[1][25]=a40;
  a40=arg[1]? arg[1][29] : 0;
  a36=(a08*a36);
  a36=(a40-a36);
  if (res[1]!=0) res[1][26]=a36;
  a36=arg[1]? arg[1][31] : 0;
  a36=(a10*a36);
  a39=(a15*a40);
  a41=(a33+a39);
  a41=(a41/a00);
  a37=(a38*a29);
  a41=(a41-a37);
  a41=(a41/a17);
  a37=arg[1]? arg[1][30] : 0;
  a41=(a41-a37);
  a41=(a14*a41);
  a41=(a41/a18);
  a41=(a13*a41);
  a41=(a20*a41);
  a41=(a12*a41);
  a42=(a22*a41);
  a43=(a19*a37);
  a43=(a21*a43);
  a42=(a42+a43);
  a36=(a36-a42);
  a42=(a23*a33);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a36=(a36+a42);
  a36=(a03*a36);
  if (res[1]!=0) res[1][27]=a36;
  a33=(a33-a39);
  a33=(a33/a00);
  a39=(a34*a29);
  a33=(a33-a39);
  a33=(a33/a16);
  a33=(a26*a33);
  a33=(a33/a27);
  a33=(a25*a33);
  a33=(a28*a33);
  a33=(a11*a33);
  a39=(a19*a41);
  a37=(a22*a37);
  a36=(a21*a37);
  a39=(a39-a36);
  a39=(a33+a39);
  a29=(a23*a29);
  a29=(a09*a29);
  a40=(a31*a40);
  a29=(a29+a40);
  a39=(a39-a29);
  a39=(a03*a39);
  if (res[1]!=0) res[1][28]=a39;
  a41=(a15*a41);
  a41=(a19*a41);
  a37=(a32*a37);
  a41=(a41-a37);
  a33=(a15*a33);
  a41=(a41-a33);
  a41=(a30*a41);
  if (res[1]!=0) res[1][29]=a41;
  if (res[1]!=0) res[1][30]=a35;
  if (res[1]!=0) res[1][31]=a35;
  a41=arg[1]? arg[1][35] : 0;
  a33=(a02*a41);
  a37=arg[1]? arg[1][34] : 0;
  a39=(a01*a37);
  a29=(a00*a39);
  a33=(a33-a29);
  a29=arg[1]? arg[1][36] : 0;
  a40=(a01*a29);
  a37=(a02*a37);
  a36=(a04*a37);
  a40=(a40+a36);
  a40=(a40/a07);
  a36=arg[1]? arg[1][33] : 0;
  a36=(a08*a36);
  a36=(a05*a36);
  a40=(a40+a36);
  a33=(a33-a40);
  if (res[1]!=0) res[1][32]=a33;
  a40=(a01*a41);
  a37=(a00*a37);
  a40=(a40+a37);
  a37=(a02*a29);
  a39=(a04*a39);
  a37=(a37-a39);
  a40=(a40+a37);
  if (res[1]!=0) res[1][33]=a40;
  a40=arg[1]? arg[1][37] : 0;
  a33=(a08*a33);
  a33=(a40-a33);
  if (res[1]!=0) res[1][34]=a33;
  a33=arg[1]? arg[1][39] : 0;
  a33=(a10*a33);
  a37=(a15*a40);
  a39=(a29+a37);
  a39=(a39/a00);
  a36=(a38*a41);
  a39=(a39-a36);
  a39=(a39/a17);
  a36=arg[1]? arg[1][38] : 0;
  a39=(a39-a36);
  a39=(a14*a39);
  a39=(a39/a18);
  a39=(a13*a39);
  a39=(a20*a39);
  a39=(a12*a39);
  a42=(a22*a39);
  a43=(a19*a36);
  a43=(a21*a43);
  a42=(a42+a43);
  a33=(a33-a42);
  a42=(a23*a29);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a33=(a33+a42);
  a33=(a03*a33);
  if (res[1]!=0) res[1][35]=a33;
  a29=(a29-a37);
  a29=(a29/a00);
  a37=(a34*a41);
  a29=(a29-a37);
  a29=(a29/a16);
  a29=(a26*a29);
  a29=(a29/a27);
  a29=(a25*a29);
  a29=(a28*a29);
  a29=(a11*a29);
  a37=(a19*a39);
  a36=(a22*a36);
  a33=(a21*a36);
  a37=(a37-a33);
  a37=(a29+a37);
  a41=(a23*a41);
  a41=(a09*a41);
  a40=(a31*a40);
  a41=(a41+a40);
  a37=(a37-a41);
  a37=(a03*a37);
  if (res[1]!=0) res[1][36]=a37;
  a39=(a15*a39);
  a39=(a19*a39);
  a36=(a32*a36);
  a39=(a39-a36);
  a29=(a15*a29);
  a39=(a39-a29);
  a39=(a30*a39);
  if (res[1]!=0) res[1][37]=a39;
  if (res[1]!=0) res[1][38]=a35;
  if (res[1]!=0) res[1][39]=a35;
  a39=arg[1]? arg[1][43] : 0;
  a29=(a02*a39);
  a36=arg[1]? arg[1][42] : 0;
  a37=(a01*a36);
  a41=(a00*a37);
  a29=(a29-a41);
  a41=arg[1]? arg[1][44] : 0;
  a40=(a01*a41);
  a36=(a02*a36);
  a33=(a04*a36);
  a40=(a40+a33);
  a40=(a40/a07);
  a33=arg[1]? arg[1][41] : 0;
  a33=(a08*a33);
  a33=(a05*a33);
  a40=(a40+a33);
  a29=(a29-a40);
  if (res[1]!=0) res[1][40]=a29;
  a40=(a01*a39);
  a36=(a00*a36);
  a40=(a40+a36);
  a36=(a02*a41);
  a37=(a04*a37);
  a36=(a36-a37);
  a40=(a40+a36);
  if (res[1]!=0) res[1][41]=a40;
  a40=arg[1]? arg[1][45] : 0;
  a29=(a08*a29);
  a29=(a40-a29);
  if (res[1]!=0) res[1][42]=a29;
  a29=arg[1]? arg[1][47] : 0;
  a29=(a10*a29);
  a36=(a15*a40);
  a37=(a41+a36);
  a37=(a37/a00);
  a33=(a38*a39);
  a37=(a37-a33);
  a37=(a37/a17);
  a33=arg[1]? arg[1][46] : 0;
  a37=(a37-a33);
  a37=(a14*a37);
  a37=(a37/a18);
  a37=(a13*a37);
  a37=(a20*a37);
  a37=(a12*a37);
  a42=(a22*a37);
  a43=(a19*a33);
  a43=(a21*a43);
  a42=(a42+a43);
  a29=(a29-a42);
  a42=(a23*a41);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a29=(a29+a42);
  a29=(a03*a29);
  if (res[1]!=0) res[1][43]=a29;
  a41=(a41-a36);
  a41=(a41/a00);
  a36=(a34*a39);
  a41=(a41-a36);
  a41=(a41/a16);
  a41=(a26*a41);
  a41=(a41/a27);
  a41=(a25*a41);
  a41=(a28*a41);
  a41=(a11*a41);
  a36=(a19*a37);
  a33=(a22*a33);
  a29=(a21*a33);
  a36=(a36-a29);
  a36=(a41+a36);
  a39=(a23*a39);
  a39=(a09*a39);
  a40=(a31*a40);
  a39=(a39+a40);
  a36=(a36-a39);
  a36=(a03*a36);
  if (res[1]!=0) res[1][44]=a36;
  a37=(a15*a37);
  a37=(a19*a37);
  a33=(a32*a33);
  a37=(a37-a33);
  a41=(a15*a41);
  a37=(a37-a41);
  a37=(a30*a37);
  if (res[1]!=0) res[1][45]=a37;
  if (res[1]!=0) res[1][46]=a35;
  if (res[1]!=0) res[1][47]=a35;
  a37=arg[1]? arg[1][51] : 0;
  a41=(a02*a37);
  a33=arg[1]? arg[1][50] : 0;
  a36=(a01*a33);
  a39=(a00*a36);
  a41=(a41-a39);
  a39=arg[1]? arg[1][52] : 0;
  a40=(a01*a39);
  a33=(a02*a33);
  a29=(a04*a33);
  a40=(a40+a29);
  a40=(a40/a07);
  a29=arg[1]? arg[1][49] : 0;
  a29=(a08*a29);
  a29=(a05*a29);
  a40=(a40+a29);
  a41=(a41-a40);
  if (res[1]!=0) res[1][48]=a41;
  a40=(a01*a37);
  a33=(a00*a33);
  a40=(a40+a33);
  a33=(a02*a39);
  a36=(a04*a36);
  a33=(a33-a36);
  a40=(a40+a33);
  if (res[1]!=0) res[1][49]=a40;
  a40=arg[1]? arg[1][53] : 0;
  a41=(a08*a41);
  a41=(a40-a41);
  if (res[1]!=0) res[1][50]=a41;
  a41=arg[1]? arg[1][55] : 0;
  a41=(a10*a41);
  a33=(a15*a40);
  a36=(a39+a33);
  a36=(a36/a00);
  a29=(a38*a37);
  a36=(a36-a29);
  a36=(a36/a17);
  a29=arg[1]? arg[1][54] : 0;
  a36=(a36-a29);
  a36=(a14*a36);
  a36=(a36/a18);
  a36=(a13*a36);
  a36=(a20*a36);
  a36=(a12*a36);
  a42=(a22*a36);
  a43=(a19*a29);
  a43=(a21*a43);
  a42=(a42+a43);
  a41=(a41-a42);
  a42=(a23*a39);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a41=(a41+a42);
  a41=(a03*a41);
  if (res[1]!=0) res[1][51]=a41;
  a39=(a39-a33);
  a39=(a39/a00);
  a33=(a34*a37);
  a39=(a39-a33);
  a39=(a39/a16);
  a39=(a26*a39);
  a39=(a39/a27);
  a39=(a25*a39);
  a39=(a28*a39);
  a39=(a11*a39);
  a33=(a19*a36);
  a29=(a22*a29);
  a41=(a21*a29);
  a33=(a33-a41);
  a33=(a39+a33);
  a37=(a23*a37);
  a37=(a09*a37);
  a40=(a31*a40);
  a37=(a37+a40);
  a33=(a33-a37);
  a33=(a03*a33);
  if (res[1]!=0) res[1][52]=a33;
  a36=(a15*a36);
  a36=(a19*a36);
  a29=(a32*a29);
  a36=(a36-a29);
  a39=(a15*a39);
  a36=(a36-a39);
  a36=(a30*a36);
  if (res[1]!=0) res[1][53]=a36;
  if (res[1]!=0) res[1][54]=a35;
  if (res[1]!=0) res[1][55]=a35;
  a36=arg[1]? arg[1][59] : 0;
  a39=(a02*a36);
  a29=arg[1]? arg[1][58] : 0;
  a33=(a01*a29);
  a37=(a00*a33);
  a39=(a39-a37);
  a37=arg[1]? arg[1][60] : 0;
  a40=(a01*a37);
  a29=(a02*a29);
  a41=(a04*a29);
  a40=(a40+a41);
  a40=(a40/a07);
  a41=arg[1]? arg[1][57] : 0;
  a41=(a08*a41);
  a41=(a05*a41);
  a40=(a40+a41);
  a39=(a39-a40);
  if (res[1]!=0) res[1][56]=a39;
  a40=(a01*a36);
  a29=(a00*a29);
  a40=(a40+a29);
  a29=(a02*a37);
  a33=(a04*a33);
  a29=(a29-a33);
  a40=(a40+a29);
  if (res[1]!=0) res[1][57]=a40;
  a40=arg[1]? arg[1][61] : 0;
  a39=(a08*a39);
  a39=(a40-a39);
  if (res[1]!=0) res[1][58]=a39;
  a39=arg[1]? arg[1][63] : 0;
  a39=(a10*a39);
  a29=(a15*a40);
  a33=(a37+a29);
  a33=(a33/a00);
  a41=(a38*a36);
  a33=(a33-a41);
  a33=(a33/a17);
  a41=arg[1]? arg[1][62] : 0;
  a33=(a33-a41);
  a33=(a14*a33);
  a33=(a33/a18);
  a33=(a13*a33);
  a33=(a20*a33);
  a33=(a12*a33);
  a42=(a22*a33);
  a43=(a19*a41);
  a43=(a21*a43);
  a42=(a42+a43);
  a39=(a39-a42);
  a42=(a23*a37);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a39=(a39+a42);
  a39=(a03*a39);
  if (res[1]!=0) res[1][59]=a39;
  a37=(a37-a29);
  a37=(a37/a00);
  a29=(a34*a36);
  a37=(a37-a29);
  a37=(a37/a16);
  a37=(a26*a37);
  a37=(a37/a27);
  a37=(a25*a37);
  a37=(a28*a37);
  a37=(a11*a37);
  a29=(a19*a33);
  a41=(a22*a41);
  a39=(a21*a41);
  a29=(a29-a39);
  a29=(a37+a29);
  a36=(a23*a36);
  a36=(a09*a36);
  a40=(a31*a40);
  a36=(a36+a40);
  a29=(a29-a36);
  a29=(a03*a29);
  if (res[1]!=0) res[1][60]=a29;
  a33=(a15*a33);
  a33=(a19*a33);
  a41=(a32*a41);
  a33=(a33-a41);
  a37=(a15*a37);
  a33=(a33-a37);
  a33=(a30*a33);
  if (res[1]!=0) res[1][61]=a33;
  if (res[1]!=0) res[1][62]=a35;
  if (res[1]!=0) res[1][63]=a35;
  a33=arg[2]? arg[2][3] : 0;
  a37=(a02*a33);
  a41=arg[2]? arg[2][2] : 0;
  a29=(a01*a41);
  a36=(a00*a29);
  a37=(a37-a36);
  a36=arg[2]? arg[2][4] : 0;
  a40=(a01*a36);
  a41=(a02*a41);
  a39=(a04*a41);
  a40=(a40+a39);
  a40=(a40/a07);
  a39=arg[2]? arg[2][1] : 0;
  a39=(a08*a39);
  a39=(a05*a39);
  a40=(a40+a39);
  a37=(a37-a40);
  if (res[2]!=0) res[2][0]=a37;
  a40=(a01*a33);
  a41=(a00*a41);
  a40=(a40+a41);
  a41=(a02*a36);
  a29=(a04*a29);
  a41=(a41-a29);
  a40=(a40+a41);
  if (res[2]!=0) res[2][1]=a40;
  a40=arg[2]? arg[2][5] : 0;
  a37=(a08*a37);
  a37=(a40-a37);
  if (res[2]!=0) res[2][2]=a37;
  a37=arg[2]? arg[2][7] : 0;
  a37=(a10*a37);
  a41=(a15*a40);
  a29=(a36+a41);
  a29=(a29/a00);
  a39=(a38*a33);
  a29=(a29-a39);
  a29=(a29/a17);
  a39=arg[2]? arg[2][6] : 0;
  a29=(a29-a39);
  a29=(a14*a29);
  a29=(a29/a18);
  a29=(a13*a29);
  a29=(a20*a29);
  a29=(a12*a29);
  a42=(a22*a29);
  a43=(a19*a39);
  a43=(a21*a43);
  a42=(a42+a43);
  a37=(a37-a42);
  a42=(a23*a36);
  a42=(a09*a42);
  a43=(a24*a40);
  a42=(a42+a43);
  a37=(a37+a42);
  a37=(a03*a37);
  if (res[2]!=0) res[2][3]=a37;
  a36=(a36-a41);
  a36=(a36/a00);
  a41=(a34*a33);
  a36=(a36-a41);
  a36=(a36/a16);
  a36=(a26*a36);
  a36=(a36/a27);
  a36=(a25*a36);
  a36=(a28*a36);
  a36=(a11*a36);
  a41=(a19*a29);
  a39=(a22*a39);
  a37=(a21*a39);
  a41=(a41-a37);
  a41=(a36+a41);
  a33=(a23*a33);
  a33=(a09*a33);
  a40=(a31*a40);
  a33=(a33+a40);
  a41=(a41-a33);
  a41=(a03*a41);
  if (res[2]!=0) res[2][4]=a41;
  a29=(a15*a29);
  a29=(a19*a29);
  a39=(a32*a39);
  a29=(a29-a39);
  a36=(a15*a36);
  a29=(a29-a36);
  a29=(a30*a29);
  if (res[2]!=0) res[2][5]=a29;
  if (res[2]!=0) res[2][6]=a06;
  if (res[2]!=0) res[2][7]=a35;
  a29=arg[2]? arg[2][11] : 0;
  a36=(a02*a29);
  a39=arg[2]? arg[2][10] : 0;
  a41=(a01*a39);
  a33=(a00*a41);
  a36=(a36-a33);
  a33=arg[2]? arg[2][12] : 0;
  a40=(a01*a33);
  a39=(a02*a39);
  a37=(a04*a39);
  a40=(a40+a37);
  a40=(a40/a07);
  a07=arg[2]? arg[2][9] : 0;
  a07=(a08*a07);
  a05=(a05*a07);
  a40=(a40+a05);
  a36=(a36-a40);
  if (res[2]!=0) res[2][8]=a36;
  a01=(a01*a29);
  a39=(a00*a39);
  a01=(a01+a39);
  a02=(a02*a33);
  a04=(a04*a41);
  a02=(a02-a04);
  a01=(a01+a02);
  if (res[2]!=0) res[2][9]=a01;
  a01=arg[2]? arg[2][13] : 0;
  a08=(a08*a36);
  a08=(a01-a08);
  if (res[2]!=0) res[2][10]=a08;
  a08=arg[2]? arg[2][15] : 0;
  a10=(a10*a08);
  a08=(a15*a01);
  a36=(a33+a08);
  a36=(a36/a00);
  a38=(a38*a29);
  a36=(a36-a38);
  a36=(a36/a17);
  a17=arg[2]? arg[2][14] : 0;
  a36=(a36-a17);
  a14=(a14*a36);
  a14=(a14/a18);
  a13=(a13*a14);
  a20=(a20*a13);
  a12=(a12*a20);
  a20=(a22*a12);
  a13=(a19*a17);
  a13=(a21*a13);
  a20=(a20+a13);
  a10=(a10-a20);
  a20=(a23*a33);
  a20=(a09*a20);
  a24=(a24*a01);
  a20=(a20+a24);
  a10=(a10+a20);
  a10=(a03*a10);
  if (res[2]!=0) res[2][11]=a10;
  a33=(a33-a08);
  a33=(a33/a00);
  a34=(a34*a29);
  a33=(a33-a34);
  a33=(a33/a16);
  a26=(a26*a33);
  a26=(a26/a27);
  a25=(a25*a26);
  a28=(a28*a25);
  a11=(a11*a28);
  a28=(a19*a12);
  a22=(a22*a17);
  a21=(a21*a22);
  a28=(a28-a21);
  a28=(a11+a28);
  a23=(a23*a29);
  a09=(a09*a23);
  a31=(a31*a01);
  a09=(a09+a31);
  a28=(a28-a09);
  a03=(a03*a28);
  if (res[2]!=0) res[2][12]=a03;
  a12=(a15*a12);
  a19=(a19*a12);
  a32=(a32*a22);
  a19=(a19-a32);
  a15=(a15*a11);
  a19=(a19-a15);
  a30=(a30*a19);
  if (res[2]!=0) res[2][13]=a30;
  if (res[2]!=0) res[2][14]=a35;
  if (res[2]!=0) res[2][15]=a06;
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Car_model_v1_expl_vde_forw_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int Car_model_v1_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Car_model_v1_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Car_model_v1_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Car_model_v1_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Car_model_v1_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Car_model_v1_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
