/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Car_model_v1_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {6, 1, 1};
static const casadi_int casadi_s3[3] = {18, 1, 1};
static const casadi_int casadi_s4[3] = {10, 1, 1};

/* Car_model_v1_expl_vde_adj:(i0[8],i1[8],i2[2],i3[6],i4[18])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[3]? arg[3][0] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a02=arg[0]? arg[0][2] : 0;
  a03=sin(a02);
  a04=(a01*a03);
  a05=1.;
  a06=arg[0]? arg[0][1] : 0;
  a06=(a06*a00);
  a06=(a05-a06);
  a04=(a04/a06);
  a04=(a04/a06);
  a07=arg[1]? arg[1][0] : 0;
  a08=arg[1]? arg[1][2] : 0;
  a09=(a00*a08);
  a07=(a07-a09);
  a04=(a04*a07);
  a00=(a00*a04);
  a00=(-a00);
  if (res[0]!=0) res[0][1]=a00;
  a02=cos(a02);
  a00=arg[0]? arg[0][3] : 0;
  a04=arg[1]? arg[1][1] : 0;
  a09=(a00*a04);
  a09=(a02*a09);
  a10=(a01*a04);
  a10=(a03*a10);
  a09=(a09-a10);
  a06=(a07/a06);
  a10=(a01*a06);
  a10=(a02*a10);
  a09=(a09-a10);
  a10=(a00*a07);
  a10=(a03*a10);
  a09=(a09-a10);
  if (res[0]!=0) res[0][2]=a09;
  a09=(a03*a04);
  a10=3.;
  a11=arg[0]? arg[0][5] : 0;
  a12=3.3333333333333331e-01;
  a13=arg[1]? arg[1][4] : 0;
  a13=(a12*a13);
  a14=(a11*a13);
  a14=(a10*a14);
  a15=1.6200000000000001e-01;
  a16=(a15*a11);
  a17=(a01-a16);
  a17=(a17/a00);
  a18=(a17/a00);
  a19=arg[4]? arg[4][3] : 0;
  a20=arg[4]? arg[4][4] : 0;
  a21=atan(a17);
  a21=(a19*a21);
  a22=atan(a21);
  a22=(a20*a22);
  a22=cos(a22);
  a23=arg[4]? arg[4][8] : 0;
  a24=6.3506579281613575e+00;
  a25=arg[1]? arg[1][5] : 0;
  a24=(a24*a25);
  a25=(a15*a24);
  a25=(a13-a25);
  a23=(a23*a25);
  a22=(a22*a23);
  a20=(a20*a22);
  a21=casadi_sq(a21);
  a21=(a05+a21);
  a20=(a20/a21);
  a19=(a19*a20);
  a17=casadi_sq(a17);
  a17=(a05+a17);
  a19=(a19/a17);
  a18=(a18*a19);
  a14=(a14+a18);
  a16=(a01+a16);
  a16=(a16/a00);
  a18=(a16/a00);
  a17=arg[4]? arg[4][0] : 0;
  a20=arg[4]? arg[4][1] : 0;
  a21=atan(a16);
  a22=arg[0]? arg[0][6] : 0;
  a21=(a21-a22);
  a21=(a17*a21);
  a23=atan(a21);
  a23=(a20*a23);
  a25=cos(a23);
  a26=arg[4]? arg[4][9] : 0;
  a27=cos(a22);
  a28=(a27*a24);
  a28=(a15*a28);
  a29=(a27*a13);
  a28=(a28+a29);
  a22=sin(a22);
  a29=arg[1]? arg[1][3] : 0;
  a12=(a12*a29);
  a29=(a22*a12);
  a28=(a28-a29);
  a28=(a26*a28);
  a25=(a25*a28);
  a20=(a20*a25);
  a21=casadi_sq(a21);
  a21=(a05+a21);
  a20=(a20/a21);
  a17=(a17*a20);
  a16=casadi_sq(a16);
  a05=(a05+a16);
  a05=(a17/a05);
  a18=(a18*a05);
  a14=(a14+a18);
  a09=(a09-a14);
  a07=(a02*a07);
  a09=(a09+a07);
  if (res[0]!=0) res[0][3]=a09;
  a19=(a19/a00);
  a11=(a11*a12);
  a11=(a10*a11);
  a11=(a19+a11);
  a05=(a05/a00);
  a11=(a11+a05);
  a02=(a02*a04);
  a11=(a11+a02);
  a03=(a03*a06);
  a11=(a11-a03);
  if (res[0]!=0) res[0][4]=a11;
  a01=(a10*a01);
  a01=(a01*a12);
  a10=(a10*a00);
  a10=(a10*a13);
  a19=(a15*a19);
  a10=(a10+a19);
  a01=(a01-a10);
  a05=(a15*a05);
  a01=(a01+a05);
  a01=(a01+a08);
  if (res[0]!=0) res[0][5]=a01;
  a23=sin(a23);
  a26=(a26*a23);
  a15=(a15*a26);
  a15=(a15*a24);
  a15=(a22*a15);
  a13=(a26*a13);
  a22=(a22*a13);
  a15=(a15+a22);
  a26=(a26*a12);
  a27=(a27*a26);
  a15=(a15+a27);
  a15=(a15+a17);
  a15=(-a15);
  if (res[0]!=0) res[0][6]=a15;
  a15=75.;
  a15=(a15*a12);
  if (res[0]!=0) res[0][7]=a15;
  a15=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][8]=a15;
  a15=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][9]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Car_model_v1_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Car_model_v1_expl_vde_adj_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Car_model_v1_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Car_model_v1_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Car_model_v1_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Car_model_v1_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Car_model_v1_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Car_model_v1_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Car_model_v1_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
