# MPC Configuration File
mpc:
  ros__parameters:
    odom_topic: "/odometry/filtered"  # EKF odometry topic
    #odom_topic: "/vesc/odom" # Vesc odometry topic

    traj_file: "traj/pts/elipse_n1000_a2.5_b1.8_v1.0.csv" # Trajectory file
    #traj_file: "traj/pts/oito_n1000_a2.5_b1.8_v1.0.csv" # Trajectory file
