# MPC Configuration File
mpc:
  ros__parameters:
    odom_topic: "/odometry/filtered"  # EKF odometry topic
    # Optional odometry topic for Vesc
    # odom_topic: "/vesc/odom"

    #pose_topic: "/pose"  # Pose topic, leave empty "" if not using pose
    pose_topic: "/tracked_pose"  # Pose topic, leave empty "" if not using pose

    traj_file: "traj/centerline_0.10_map_2025-10-15_16-33-33.csv" # Trajectory file
    #traj_file: "traj/pts/oito_n1000_a2.5_b1.8_v1.0.csv" # Trajectory file

    v_x_ref: 10.0  # Reference velocity in m/s

    cost_weights:
      w_n: 5.0          # Weight for lateral error
      w_u: 5.0          # Weight for steering input
      w_vx: 10.0         # Weight for velocity error
      w_r: 5.0          # Weight for yaw rate
      w_dsteering: 5.0 # Weight for steering rate
      w_dvelocity: 100.0  # Weight for acceleration

    frame_id: "map"  # Frame ID for the trajectory
