ekf_filter_node: #Config 388
  ros__parameters:
    frequency: 50.0
    two_d_mode: False
    publish_tf: False
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"
    sensor_timeout: 2.0 # segundo de espera antes de declarar timeout
    publish_acceleration: True
    print_diagnostics: True
    #use_sim_time: True
    #transform_timeout: 0.1
    
    odom0: "vesc/odom"
    odom0_config: [false, false, true,   # X, Y, Z
                   false, false, true,  # Roll, Pitch, Yaw
                   true, true, false,   # dX, dY, dZ
                   false, false, true,  # dRoll, dPitch, dYaw
                   false, false, false] # Acceleration (X, Y, Z)

    #Forza Config
    #odom0_config: [false, false, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              true, true, false,   # dX, dY, dZ
    #              false, false, false,  # dRoll, dPitch, dYaw
    #              false, false, false] # Acceleration (X, Y, Z)

    #odom1: "zed/zed_node/odom"
    #odom1_config: [true, true, false,
    #               false, false, true,
    #               true, true, false,
    #               false, false, true,
    #               false, false, false]

    #pose0: "pose"
    #pose0_config: [true, true, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              false, false, false,  # dRoll, dPitch, dYaw
    #              false, false, false] # Acceleration (X, Y, Z)


#
    imu0: "imu/data"
    #imu0: "vesc/imu/raw"
    #imu0: "zed2i/imu/data"

    imu0_remove_gravitational_acceleration: true
    imu0_relative: false

    imu0_config: [false, false, false,   # X, Y, Z
                  true, true, true,  # Roll, Pitch, Yaw
                  false, false, false,   # dX, dY, dZ
                  true, true, true,  # dRoll, dPitch, dYaw
                  true, true, true] # Acceleration (X, Y, Z)

    #Without Acceleration
    #imu0_config: [false, false, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              false, false, true,  # dRoll, dPitch, dYaw
    #              false, false, false] # Acceleration (X, Y, Z)



    #Forza Config
    #imu0_config: [false, false, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              false, false, true,  # dRoll, dPitch, dYaw
    #              false, false, false] # Acceleration (X, Y, Z)


                  
    
    #imu1: "vesc/imu/raw"
    #imu1_remove_gravitational_acceleration: true
    #imu1_relative: true

    #imu1_config: [false, false, false,
    #              true, true,true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              true, true, true,  # dRoll, dPitch, dYaw
    #              true, true, true]

    #Without Acceleration
    #imu1_config: [false, false, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              false, false, true,  # dRoll, dPitch, dYaw
    #              false, false, false] # Acceleration (X, Y, Z)


    #imu1_config: [false, false, false,   # X, Y, Z
    #              false, false, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              false, false, true,  # dRoll, dPitch, dYaw
    #              true, true, false] # Acceleration (X, Y, Z)
    #imu1_remove_gravitational_acceleration: True
    #imu1_relative: True

    
    
    #imu2: "zed2i/imu/data"
    #imu2_remove_gravitational_acceleration: false
    #imu2_relative: true
#
    #imu2_config: [false, false, false,
    #              true, true, true,  # Roll, Pitch, Yaw
    #              false, false, false,   # dX, dY, dZ
    #              true, true, true,  # dRoll, dPitch, dYaw
    #              true, true, true]
    