ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: True
    publish_tf: True
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"
    sensor_timeout: 2.0 # segundo de espera antes de declarar timeout
    publish_acceleration: True
    print_diagnostics: True
    use_sim_time: True
    
    odom0: "vesc/odom"
    #odom0_config: [true, true, false,   # X, Y, Z
    #               false, false, true,  # Roll, Pitch, Yaw
    #               true, true, false,   # dX, dY, dZ
    #               false, false, true,  # dRoll, dPitch, dYaw
    #               false, false, false] # Acceleration (X, Y, Z)

    #Forza Config
    odom0_config: [false, false, false,   # X, Y, Z
                  false, false, true,  # Roll, Pitch, Yaw
                  true, true, false,   # dX, dY, dZ
                  false, false, false,  # dRoll, dPitch, dYaw
                  false, false, false] # Acceleration (X, Y, Z)

    #odom1: "zed/zed_node/odom"
    #odom1_config: [true, true, false,
    #               false, false, true,
    #               true, true, false,
    #               false, false, true,
    #               false, false, false]
#
    imu0: "imu/data"
    #imu0_config: [false, false, false,
    #              true, true, true, # Roll, Pitch, Yaw
    #              false, false, false,
    #              false, false, true,
    #              true, true, false]

    #Forza Config
    imu0_config: [false, false, false,   # X, Y, Z
                  false, false, true,  # Roll, Pitch, Yaw
                  false, false, false,   # dX, dY, dZ
                  false, false, true,  # dRoll, dPitch, dYaw
                  false, false, false] # Acceleration (X, Y, Z)

    #imu1_config:  [false, false, false,
    #              true, true, true,
    #              false, false, false,
    #              true, true, true,
    #              true, true, true]
    imu0_remove_gravitational_acceleration: True   
    imu0_relative: True

                  
    
    #imu1: "vesc/imu/raw"
    #imu1_config: [false, false, false,
    #              true, true, true, # Roll, Pitch, Yaw
    #              false, false, false,
    #              false, false, true,
    #              true, true, false]
    #imu1_remove_gravitational_acceleration: True
    #imu1_relative: True

    
    
    
    #imu1: "zed/zed_node/imu/data"
    #imu0_config: [true, true, true,
    #              true, true, true,
    #              true, true, true,
    #              true, true, true,
    #              true, true, true]
