slam_toolbox:
  ros__parameters:
    odom_frame : "odom"
    map_frame : "world"
    base_frame : "laser"
    scan_topic : "/scan"
    scan_queue_size : 0
    min_laser_range : 0.06 
    max_laser_range : 5.6
    use_scan_matching : true
    #mode: localization
    use_sim_time : false
    #tf_buffer_duration : 9999999999999999999999999999999999999999999999999999999999999999999999999999999.0

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
