/*
solverMPCC : A fast customized optimization solver.

Copyright (C) 2013-2023 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.3.0 on Friday, April 4, 2025 at 9:51:44 AM */
#ifndef solverMPCC_H
#define solverMPCC_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double solverMPCC_float;
typedef double solverMPCC_ldl_s_float;
typedef double solverMPCC_ldl_r_float;
typedef double solverMPCC_callback_float;

typedef double solverMPCCinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_solverMPCC
#define MISRA_C_solverMPCC (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_solverMPCC
#define RESTRICT_CODE_solverMPCC (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_solverMPCC
#define SET_PRINTLEVEL_solverMPCC    (0)
#endif

/* timing */
#ifndef SET_TIMING_solverMPCC
#define SET_TIMING_solverMPCC    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_solverMPCC			(1000000)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_solverMPCC		(solverMPCC_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_solverMPCC	(1000000) 

/* whether callback return values should be checked */
#define EXTFUNC_RETURN_solverMPCC (0)

/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_solverMPCC      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_solverMPCC (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_solverMPCC   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_solverMPCC (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_solverMPCC  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_solverMPCC   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_solverMPCC  (-6)

/* invalid value (<= -100) returned by external function */
#define INVALIDFUNCEXIT_solverMPCC (-200)

/* bad value returned by external function */
#define BADFUNCEXIT_solverMPCC(status) (status > -100? status - 200 : INVALIDFUNCEXIT_solverMPCC)

/* no progress in method possible */
#define NOPROGRESS_solverMPCC   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_solverMPCC   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_solverMPCC   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_solverMPCC   (-12)

/* thread error */
#define THREAD_FAILURE_solverMPCC  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_solverMPCC  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_solverMPCC  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_solverMPCC (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_solverMPCC (-102)


/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct solverMPCC_mem solverMPCC_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern solverMPCC_mem * solverMPCC_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t solverMPCC_get_mem_size( void );
extern size_t solverMPCC_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 859 */
    solverMPCC_float x0[859];

    /* vector of size 14 */
    solverMPCC_float xinit[14];

    /* vector of size 21471 */
    solverMPCC_float all_parameters[21471];

    /* scalar */
    solverMPCC_float solver_timeout;

    /* scalar */
    solver_int32_unsigned num_of_threads;


} solverMPCC_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* column vector of length 833 */
    solverMPCC_float z[833];

    /* column vector of length 15 */
    solverMPCC_float zN_1[15];

    /* column vector of length 11 */
    solverMPCC_float zN[11];


} solverMPCC_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    solverMPCC_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    solverMPCC_float res_ineq;

    /* scalar: norm of stationarity condition */
    solverMPCC_float rsnorm;

    /* scalar: max of all complementarity violations */
    solverMPCC_float rcompnorm;

    /* scalar: primal objective */
    solverMPCC_float pobj;

    /* scalar: dual objective */
    solverMPCC_float dobj;

    /* scalar: duality gap := pobj - dobj */
    solverMPCC_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    solverMPCC_float rdgap;

    /* scalar: duality measure */
    solverMPCC_float mu;

    /* scalar: duality measure (after affine step) */
    solverMPCC_float mu_aff;

    /* scalar: centering parameter */
    solverMPCC_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    solverMPCC_float step_aff;

    /* scalar: step size (combined direction) */
    solverMPCC_float step_cc;

    /* scalar: total solve time */
    solverMPCC_float solvetime;

    /* scalar: time spent in function evaluations */
    solverMPCC_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];






} solverMPCC_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Friday, April 4, 2025 9:51:49 AM */
/* User License expires on: (UTC) Friday, April 11, 2025 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Friday, April 11, 2025 10:00:00 PM (approx.) */
/* Solver Id: 50d44796-cda8-44d0-ab5d-a464eac59428 */
/* Host Compiler Version: d76500f0 */
/* Target Compiler Version: unused */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*solverMPCC_extfunc)(solverMPCC_float* x, solverMPCC_float* y, solverMPCC_float* lambda, solverMPCC_float* params, solverMPCC_float* pobj, solverMPCC_float* g, solverMPCC_float* c, solverMPCC_float* Jeq, solverMPCC_float* h, solverMPCC_float* Jineq, solverMPCC_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default solverMPCC_solve(solverMPCC_params *params, solverMPCC_output *output, solverMPCC_info *info, solverMPCC_mem *mem, FILE *fs, solverMPCC_extfunc evalextfunctions_solverMPCC);











#ifdef __cplusplus
}
#endif

#endif
