
#ifndef SOLVERTV_CASADI_H
#define SOLVERTV_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int solverTV_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_objective_1_sparsity_out(casadi_int i);
int solverTV_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_dynamics_1_sparsity_out(casadi_int i);
int solverTV_dynamics_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_inequalities_1_sparsity_out(casadi_int i);
int solverTV_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_objective_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_objective_2_sparsity_out(casadi_int i);
int solverTV_objective_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_dynamics_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_dynamics_2_sparsity_out(casadi_int i);
int solverTV_dynamics_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_inequalities_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_inequalities_2_sparsity_out(casadi_int i);
int solverTV_inequalities_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_objective_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_objective_14_sparsity_out(casadi_int i);
int solverTV_objective_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_dynamics_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_dynamics_14_sparsity_out(casadi_int i);
int solverTV_dynamics_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_inequalities_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_inequalities_14_sparsity_out(casadi_int i);
int solverTV_inequalities_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_objective_15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_objective_15_sparsity_out(casadi_int i);
int solverTV_objective_15_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solverTV_inequalities_15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

const casadi_int* solverTV_inequalities_15_sparsity_out(casadi_int i);
int solverTV_inequalities_15_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
