/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) car_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[19] = {4, 4, 0, 3, 6, 9, 12, 0, 1, 3, 0, 1, 3, 0, 1, 3, 0, 1, 3};
static const casadi_int casadi_s1[7] = {4, 2, 0, 1, 2, 2, 3};
static const casadi_int casadi_s2[9] = {2, 4, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s3[11] = {4, 2, 0, 3, 6, 0, 1, 3, 0, 1, 3};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s6[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};

/* car_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, *w9=w+24, *w10=w+28, *w11=w+32, *w12=w+36, w13, w14, w15, w16, *w18=w+44, w19, *w20=w+48, *w21=w+51, *w22=w+54, *w23=w+57, *w24=w+69, *w26=w+71, *w27=w+73, *w28=w+75, *w29=w+83, *w30=w+91;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = input[3][0] */
  w4 = arg[3] ? arg[3][0] : 0;
  /* #9: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #10: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #11: @5 = tan(@4) */
  w5 = tan( w4 );
  /* #12: @6 = (@0*@5) */
  w6  = (w0*w5);
  /* #13: @7 = 2.5 */
  w7 = 2.5000000000000000e+00;
  /* #14: @6 = (@6/@7) */
  w6 /= w7;
  /* #15: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #16: @8 = input[1][0] */
  casadi_copy(arg[1], 16, w8);
  /* #17: {@9, @10, @11, @12} = horzsplit(@8) */
  casadi_copy(w8, 4, w9);
  casadi_copy(w8+4, 4, w10);
  casadi_copy(w8+8, 4, w11);
  casadi_copy(w8+12, 4, w12);
  /* #18: {NULL, NULL, @6, @7} = vertsplit(@9) */
  w6 = w9[2];
  w7 = w9[3];
  /* #19: @13 = (@2*@6) */
  w13  = (w2*w6);
  /* #20: @14 = sin(@1) */
  w14 = sin( w1 );
  /* #21: @15 = (@14*@7) */
  w15  = (w14*w7);
  /* #22: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #23: @13 = (@13-@15) */
  w13 -= w15;
  /* #24: @15 = (@3*@6) */
  w15  = (w3*w6);
  /* #25: @16 = cos(@1) */
  w16 = cos( w1 );
  /* #26: @7 = (@16*@7) */
  w7  = (w16*w7);
  /* #27: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #28: @15 = (@15+@7) */
  w15 += w7;
  /* #29: @17 = 00 */
  /* #30: @7 = 0.4 */
  w7 = 4.0000000000000002e-01;
  /* #31: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #32: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #33: @18 = vertcat(@13, @15, @17, @6) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w6;
  /* #34: {NULL, NULL, @13, @15} = vertsplit(@10) */
  w13 = w10[2];
  w15 = w10[3];
  /* #35: @6 = (@2*@13) */
  w6  = (w2*w13);
  /* #36: @19 = (@14*@15) */
  w19  = (w14*w15);
  /* #37: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #38: @6 = (@6-@19) */
  w6 -= w19;
  /* #39: @19 = (@3*@13) */
  w19  = (w3*w13);
  /* #40: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #41: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #42: @19 = (@19+@15) */
  w19 += w15;
  /* #43: @17 = 00 */
  /* #44: @13 = (@5*@13) */
  w13  = (w5*w13);
  /* #45: @13 = (@7*@13) */
  w13  = (w7*w13);
  /* #46: @20 = vertcat(@6, @19, @17, @13) */
  rr=w20;
  *rr++ = w6;
  *rr++ = w19;
  *rr++ = w13;
  /* #47: {NULL, NULL, @6, @19} = vertsplit(@11) */
  w6 = w11[2];
  w19 = w11[3];
  /* #48: @13 = (@2*@6) */
  w13  = (w2*w6);
  /* #49: @15 = (@14*@19) */
  w15  = (w14*w19);
  /* #50: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #51: @13 = (@13-@15) */
  w13 -= w15;
  /* #52: @15 = (@3*@6) */
  w15  = (w3*w6);
  /* #53: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #54: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #55: @15 = (@15+@19) */
  w15 += w19;
  /* #56: @17 = 00 */
  /* #57: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #58: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #59: @21 = vertcat(@13, @15, @17, @6) */
  rr=w21;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w6;
  /* #60: {NULL, NULL, @13, @15} = vertsplit(@12) */
  w13 = w12[2];
  w15 = w12[3];
  /* #61: @6 = (@2*@13) */
  w6  = (w2*w13);
  /* #62: @14 = (@14*@15) */
  w14 *= w15;
  /* #63: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #64: @6 = (@6-@14) */
  w6 -= w14;
  /* #65: @14 = (@3*@13) */
  w14  = (w3*w13);
  /* #66: @16 = (@16*@15) */
  w16 *= w15;
  /* #67: @16 = (@0*@16) */
  w16  = (w0*w16);
  /* #68: @14 = (@14+@16) */
  w14 += w16;
  /* #69: @17 = 00 */
  /* #70: @13 = (@5*@13) */
  w13  = (w5*w13);
  /* #71: @7 = (@7*@13) */
  w7 *= w13;
  /* #72: @22 = vertcat(@6, @14, @17, @7) */
  rr=w22;
  *rr++ = w6;
  *rr++ = w14;
  *rr++ = w7;
  /* #73: @23 = horzcat(@18, @20, @21, @22) */
  rr=w23;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #74: @8 = dense(@23) */
  casadi_densify(w23, casadi_s0, w8, 0);
  /* #75: output[1][0] = @8 */
  casadi_copy(w8, 16, res[1]);
  /* #76: @24 = zeros(2x4,2nz) */
  casadi_clear(w24, 2);
  /* #77: @17 = 00 */
  /* #78: @25 = 00 */
  /* #79: @26 = ones(2x1) */
  casadi_fill(w26, 2, 1.);
  /* #80: {@6, @14} = vertsplit(@26) */
  w6 = w26[0];
  w14 = w26[1];
  /* #81: @7 = 0.4 */
  w7 = 4.0000000000000002e-01;
  /* #82: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #83: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #84: @14 = (@14/@4) */
  w14 /= w4;
  /* #85: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #86: @7 = (@7*@14) */
  w7 *= w14;
  /* #87: @26 = vertcat(@17, @25, @6, @7) */
  rr=w26;
  *rr++ = w6;
  *rr++ = w7;
  /* #88: @27 = @26[:2] */
  for (rr=w27, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #89: (@24[:2] = @27) */
  for (rr=w24+0, ss=w27; rr!=w24+2; rr+=1) *rr = *ss++;
  /* #90: @27 = @24' */
  casadi_trans(w24,casadi_s2, w27, casadi_s1, iw);
  /* #91: @28 = dense(@27) */
  casadi_densify(w27, casadi_s1, w28, 0);
  /* #92: @29 = input[2][0] */
  casadi_copy(arg[2], 8, w29);
  /* #93: {@12, @11} = horzsplit(@29) */
  casadi_copy(w29, 4, w12);
  casadi_copy(w29+4, 4, w11);
  /* #94: {NULL, NULL, @6, @7} = vertsplit(@12) */
  w6 = w12[2];
  w7 = w12[3];
  /* #95: @14 = (@2*@6) */
  w14  = (w2*w6);
  /* #96: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #97: @13 = (@4*@7) */
  w13  = (w4*w7);
  /* #98: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #99: @14 = (@14-@13) */
  w14 -= w13;
  /* #100: @13 = (@3*@6) */
  w13  = (w3*w6);
  /* #101: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #102: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #103: @7 = (@0*@7) */
  w7  = (w0*w7);
  /* #104: @13 = (@13+@7) */
  w13 += w7;
  /* #105: @17 = 00 */
  /* #106: @7 = 0.4 */
  w7 = 4.0000000000000002e-01;
  /* #107: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #108: @6 = (@7*@6) */
  w6  = (w7*w6);
  /* #109: @18 = vertcat(@14, @13, @17, @6) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w6;
  /* #110: {NULL, NULL, @14, @13} = vertsplit(@11) */
  w14 = w11[2];
  w13 = w11[3];
  /* #111: @2 = (@2*@14) */
  w2 *= w14;
  /* #112: @4 = (@4*@13) */
  w4 *= w13;
  /* #113: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #114: @2 = (@2-@4) */
  w2 -= w4;
  /* #115: @3 = (@3*@14) */
  w3 *= w14;
  /* #116: @1 = (@1*@13) */
  w1 *= w13;
  /* #117: @0 = (@0*@1) */
  w0 *= w1;
  /* #118: @3 = (@3+@0) */
  w3 += w0;
  /* #119: @17 = 00 */
  /* #120: @5 = (@5*@14) */
  w5 *= w14;
  /* #121: @7 = (@7*@5) */
  w7 *= w5;
  /* #122: @20 = vertcat(@2, @3, @17, @7) */
  rr=w20;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  /* #123: @30 = horzcat(@18, @20) */
  rr=w30;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  /* #124: @29 = dense(@30) */
  casadi_densify(w30, casadi_s3, w29, 0);
  /* #125: @28 = (@28+@29) */
  for (i=0, rr=w28, cs=w29; i<8; ++i) (*rr++) += (*cs++);
  /* #126: output[2][0] = @28 */
  casadi_copy(w28, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void car_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int car_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int car_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real car_model_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_model_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_model_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int car_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 97;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
