/*
solverTV : A fast customized optimization solver.

Copyright (C) 2013-2023 EMBOTECH AG [info@embotech.com]. All rights reserved.


This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.3.0 on Monday, July 8, 2024 at 12:56:53 PM */
#ifndef solverTV_H
#define solverTV_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif
#ifndef SOLVER_STRING_H
#define SOLVER_STRING_H
#include <string.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double solverTV_float;
typedef double solverTV_ldl_s_float;
typedef double solverTV_ldl_r_float;
typedef double solverTV_callback_float;

typedef double solverTVinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_solverTV
#define MISRA_C_solverTV (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_solverTV
#define RESTRICT_CODE_solverTV (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_solverTV
#define SET_PRINTLEVEL_solverTV    (0)
#endif

/* timing */
#ifndef SET_TIMING_solverTV
#define SET_TIMING_solverTV    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_solverTV			(1000000)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_solverTV		(solverTV_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_solverTV	(1000000) 

/* whether callback return values should be checked */
#define EXTFUNC_RETURN_solverTV (0)

/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_solverTV      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_solverTV (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_solverTV   (2)

/* solver stopped externally */
#define EXIT_EXTERNAL_solverTV (3)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_solverTV  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_solverTV   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_solverTV  (-6)

/* invalid value (<= -100) returned by external function */
#define INVALIDFUNCEXIT_solverTV (-200)

/* bad value returned by external function */
#define BADFUNCEXIT_solverTV(status) (status > -100? status - 200 : INVALIDFUNCEXIT_solverTV)

/* no progress in method possible */
#define NOPROGRESS_solverTV   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_solverTV   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_solverTV   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_solverTV   (-12)

/* thread error */
#define THREAD_FAILURE_solverTV  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_solverTV  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_solverTV  (-100)

/* Insufficient number of internal memory instances.
 * Increase codeoptions.max_num_mem. */
#define MEMORY_INVALID_solverTV (-101)
/* Number of threads larger than specified.
 * Increase codeoptions.nlp.max_num_threads. */
#define NUMTHREADS_INVALID_solverTV (-102)


/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)


/* MEMORY STRUCT --------------------------------------------------------*/
typedef struct solverTV_mem solverTV_mem;
#ifdef __cplusplus
extern "C" {
#endif
/* MEMORY STRUCT --------------------------------------------------------*/
extern solverTV_mem * solverTV_external_mem(void * mem_ptr, solver_int32_unsigned i_mem, size_t mem_size);
extern size_t solverTV_get_mem_size( void );
extern size_t solverTV_get_const_size( void );
#ifdef __cplusplus
}
#endif

/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 4 */
    solverTV_float xinit[4];

    /* vector of size 145 */
    solverTV_float x0[145];

    /* vector of size 630 */
    solverTV_float all_parameters[630];

    /* scalar */
    solverTV_float solver_timeout;

    /* scalar */
    solver_int32_unsigned num_of_threads;


} solverTV_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* column vector of length 10 */
    solverTV_float zI[10];

    /* column vector of length 130 */
    solverTV_float z[130];

    /* column vector of length 5 */
    solverTV_float zN[5];


} solverTV_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* scalar: iteration number */
    solver_int32_default it;

    /* scalar: number of iterations needed to optimality (branch-and-bound) */
    solver_int32_default it2opt;

    /* scalar: inf-norm of equality constraint residuals */
    solverTV_float res_eq;

    /* scalar: inf-norm of inequality constraint residuals */
    solverTV_float res_ineq;

    /* scalar: norm of stationarity condition */
    solverTV_float rsnorm;

    /* scalar: max of all complementarity violations */
    solverTV_float rcompnorm;

    /* scalar: primal objective */
    solverTV_float pobj;

    /* scalar: dual objective */
    solverTV_float dobj;

    /* scalar: duality gap := pobj - dobj */
    solverTV_float dgap;

    /* scalar: relative duality gap := |dgap / pobj | */
    solverTV_float rdgap;

    /* scalar: duality measure */
    solverTV_float mu;

    /* scalar: duality measure (after affine step) */
    solverTV_float mu_aff;

    /* scalar: centering parameter */
    solverTV_float sigma;

    /* scalar: number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;

    /* scalar: number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;

    /* scalar: step size (affine direction) */
    solverTV_float step_aff;

    /* scalar: step size (combined direction) */
    solverTV_float step_cc;

    /* scalar: total solve time */
    solverTV_float solvetime;

    /* scalar: time spent in function evaluations */
    solverTV_float fevalstime;

    /* column vector of length 8: solver ID of FORCESPRO solver */
    solver_int32_default solver_id[8];






} solverTV_info;







/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Monday, July 8, 2024 12:56:55 PM */
/* User License expires on: (UTC) Sunday, April 27, 2025 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Sunday, April 27, 2025 10:00:00 PM (approx.) */
/* Solver Id: 58510aee-8507-4d3a-9836-3b249507162b */
/* Host Compiler Version: d76500f0 */
/* Target Compiler Version: unused */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef solver_int32_default (*solverTV_extfunc)(solverTV_float* x, solverTV_float* y, solverTV_float* lambda, solverTV_float* params, solverTV_float* pobj, solverTV_float* g, solverTV_float* c, solverTV_float* Jeq, solverTV_float* h, solverTV_float* Jineq, solverTV_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default solverTV_solve(solverTV_params *params, solverTV_output *output, solverTV_info *info, solverTV_mem *mem, FILE *fs, solverTV_extfunc evalextfunctions_solverTV);











#ifdef __cplusplus
}
#endif

#endif
