/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mpc_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {5, 5, 1};
static const casadi_int casadi_s2[3] = {5, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* mpc_model_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4)->(o0[5],o1[5x5],o2[5x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15;
  a00=arg[3]? arg[3][1] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  if (res[0]!=0) res[0][0]=a03;
  a01=sin(a01);
  a03=(a00*a01);
  if (res[0]!=0) res[0][1]=a03;
  a03=arg[0]? arg[0][4] : 0;
  a04=(a00+a03);
  a05=2.;
  a04=(a04/a05);
  a06=3.4999999999999998e-01;
  a04=(a04/a06);
  a06=arg[0]? arg[0][3] : 0;
  a07=5.2359999999999998e+00;
  a08=arg[3]? arg[3][0] : 0;
  a09=(a08-a06);
  a10=arg[4]? arg[4][0] : 0;
  a09=(a09/a10);
  a11=(a07<a09);
  a07=(a11?a07:0);
  a11=(!a11);
  a12=-5.2359999999999998e+00;
  a13=(a09<a12);
  a12=(a13?a12:0);
  a13=(!a13);
  a09=(a13?a09:0);
  a12=(a12+a09);
  a12=(a11?a12:0);
  a07=(a07+a12);
  a12=(a07*a10);
  a06=(a06+a12);
  a06=(a06+a08);
  a06=(a06/a05);
  a05=tan(a06);
  a08=(a04*a05);
  if (res[0]!=0) res[0][2]=a08;
  if (res[0]!=0) res[0][3]=a07;
  a03=(a00-a03);
  a03=(a03/a10);
  if (res[0]!=0) res[0][4]=a03;
  a03=arg[1]? arg[1][2] : 0;
  a07=(a01*a03);
  a07=(a00*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][0]=a07;
  a03=(a02*a03);
  a03=(a00*a03);
  if (res[1]!=0) res[1][1]=a03;
  a03=2.8571428571428572e+00;
  a07=5.0000000000000000e-01;
  a08=arg[1]? arg[1][4] : 0;
  a12=(a07*a08);
  a12=(a03*a12);
  a12=(a05*a12);
  a09=arg[1]? arg[1][3] : 0;
  a14=(-a09);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  a14=(a09+a14);
  a14=(a07*a14);
  a06=cos(a06);
  a06=casadi_sq(a06);
  a14=(a14/a06);
  a14=(a04*a14);
  a12=(a12+a14);
  if (res[1]!=0) res[1][2]=a12;
  a09=(a09/a10);
  a09=(-a09);
  a09=(a13?a09:0);
  a09=(a11?a09:0);
  if (res[1]!=0) res[1][3]=a09;
  a08=(a08/a10);
  a08=(-a08);
  if (res[1]!=0) res[1][4]=a08;
  a08=arg[1]? arg[1][7] : 0;
  a09=(a01*a08);
  a09=(a00*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][5]=a09;
  a08=(a02*a08);
  a08=(a00*a08);
  if (res[1]!=0) res[1][6]=a08;
  a08=arg[1]? arg[1][9] : 0;
  a09=(a07*a08);
  a09=(a03*a09);
  a09=(a05*a09);
  a12=arg[1]? arg[1][8] : 0;
  a14=(-a12);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  a14=(a12+a14);
  a14=(a07*a14);
  a14=(a14/a06);
  a14=(a04*a14);
  a09=(a09+a14);
  if (res[1]!=0) res[1][7]=a09;
  a12=(a12/a10);
  a12=(-a12);
  a12=(a13?a12:0);
  a12=(a11?a12:0);
  if (res[1]!=0) res[1][8]=a12;
  a08=(a08/a10);
  a08=(-a08);
  if (res[1]!=0) res[1][9]=a08;
  a08=arg[1]? arg[1][12] : 0;
  a12=(a01*a08);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][10]=a12;
  a08=(a02*a08);
  a08=(a00*a08);
  if (res[1]!=0) res[1][11]=a08;
  a08=arg[1]? arg[1][14] : 0;
  a12=(a07*a08);
  a12=(a03*a12);
  a12=(a05*a12);
  a09=arg[1]? arg[1][13] : 0;
  a14=(-a09);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  a14=(a09+a14);
  a14=(a07*a14);
  a14=(a14/a06);
  a14=(a04*a14);
  a12=(a12+a14);
  if (res[1]!=0) res[1][12]=a12;
  a09=(a09/a10);
  a09=(-a09);
  a09=(a13?a09:0);
  a09=(a11?a09:0);
  if (res[1]!=0) res[1][13]=a09;
  a08=(a08/a10);
  a08=(-a08);
  if (res[1]!=0) res[1][14]=a08;
  a08=arg[1]? arg[1][17] : 0;
  a09=(a01*a08);
  a09=(a00*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][15]=a09;
  a08=(a02*a08);
  a08=(a00*a08);
  if (res[1]!=0) res[1][16]=a08;
  a08=arg[1]? arg[1][19] : 0;
  a09=(a07*a08);
  a09=(a03*a09);
  a09=(a05*a09);
  a12=arg[1]? arg[1][18] : 0;
  a14=(-a12);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  a14=(a12+a14);
  a14=(a07*a14);
  a14=(a14/a06);
  a14=(a04*a14);
  a09=(a09+a14);
  if (res[1]!=0) res[1][17]=a09;
  a12=(a12/a10);
  a12=(-a12);
  a12=(a13?a12:0);
  a12=(a11?a12:0);
  if (res[1]!=0) res[1][18]=a12;
  a08=(a08/a10);
  a08=(-a08);
  if (res[1]!=0) res[1][19]=a08;
  a08=arg[1]? arg[1][22] : 0;
  a12=(a01*a08);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][20]=a12;
  a08=(a02*a08);
  a08=(a00*a08);
  if (res[1]!=0) res[1][21]=a08;
  a08=arg[1]? arg[1][24] : 0;
  a12=(a07*a08);
  a12=(a03*a12);
  a12=(a05*a12);
  a09=arg[1]? arg[1][23] : 0;
  a14=(-a09);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  a14=(a09+a14);
  a14=(a07*a14);
  a14=(a14/a06);
  a14=(a04*a14);
  a12=(a12+a14);
  if (res[1]!=0) res[1][22]=a12;
  a09=(a09/a10);
  a09=(-a09);
  a09=(a13?a09:0);
  a09=(a11?a09:0);
  if (res[1]!=0) res[1][23]=a09;
  a08=(a08/a10);
  a08=(-a08);
  if (res[1]!=0) res[1][24]=a08;
  a08=arg[2]? arg[2][2] : 0;
  a09=(a01*a08);
  a09=(a00*a09);
  a09=(-a09);
  if (res[2]!=0) res[2][0]=a09;
  a08=(a02*a08);
  a08=(a00*a08);
  if (res[2]!=0) res[2][1]=a08;
  a08=1.;
  a09=(a13?a08:0);
  a09=(a11?a09:0);
  a09=(a09+a08);
  a09=(a07*a09);
  a09=(a09/a06);
  a09=(a04*a09);
  a08=arg[2]? arg[2][4] : 0;
  a12=(a07*a08);
  a12=(a03*a12);
  a12=(a05*a12);
  a14=arg[2]? arg[2][3] : 0;
  a15=(-a14);
  a15=(a13?a15:0);
  a15=(a11?a15:0);
  a15=(a14+a15);
  a15=(a07*a15);
  a15=(a15/a06);
  a15=(a04*a15);
  a12=(a12+a15);
  a09=(a09+a12);
  if (res[2]!=0) res[2][2]=a09;
  a09=(1./a10);
  a14=(a14/a10);
  a14=(a09-a14);
  a14=(a13?a14:0);
  a14=(a11?a14:0);
  if (res[2]!=0) res[2][3]=a14;
  a08=(a08/a10);
  a08=(-a08);
  if (res[2]!=0) res[2][4]=a08;
  a08=arg[2]? arg[2][7] : 0;
  a14=(a01*a08);
  a14=(a00*a14);
  a14=(a02-a14);
  if (res[2]!=0) res[2][5]=a14;
  a02=(a02*a08);
  a00=(a00*a02);
  a01=(a01+a00);
  if (res[2]!=0) res[2][6]=a01;
  a01=1.4285714285714286e+00;
  a01=(a01*a05);
  a00=arg[2]? arg[2][9] : 0;
  a02=(a07*a00);
  a03=(a03*a02);
  a05=(a05*a03);
  a03=arg[2]? arg[2][8] : 0;
  a02=(-a03);
  a02=(a13?a02:0);
  a02=(a11?a02:0);
  a02=(a03+a02);
  a07=(a07*a02);
  a07=(a07/a06);
  a04=(a04*a07);
  a05=(a05+a04);
  a01=(a01+a05);
  if (res[2]!=0) res[2][7]=a01;
  a03=(a03/a10);
  a03=(-a03);
  a13=(a13?a03:0);
  a11=(a11?a13:0);
  if (res[2]!=0) res[2][8]=a11;
  a00=(a00/a10);
  a09=(a09-a00);
  if (res[2]!=0) res[2][9]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mpc_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mpc_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mpc_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mpc_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mpc_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mpc_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mpc_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mpc_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mpc_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
