/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) solverTV_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[46] = {42, 1, 0, 42, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[20] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[28] = {4, 10, 0, 2, 4, 6, 8, 8, 8, 8, 11, 13, 15, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 3, 2, 3, 2, 3};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[21] = {8, 10, 0, 2, 4, 6, 8, 8, 8, 8, 8, 8, 8, 0, 4, 1, 5, 2, 6, 3, 7};
static const casadi_int casadi_s8[22] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s9[26] = {10, 10, 0, 2, 4, 6, 8, 9, 10, 10, 10, 12, 13, 0, 4, 1, 5, 2, 6, 3, 7, 8, 9, 8, 9, 9};
static const casadi_int casadi_s10[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s11[24] = {3, 10, 0, 1, 2, 3, 4, 4, 4, 4, 7, 9, 11, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 2};
static const casadi_int casadi_s12[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s13[12] = {1, 5, 0, 1, 2, 3, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s14[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s15[13] = {2, 5, 0, 1, 2, 2, 4, 5, 0, 1, 0, 1, 1};

/* solverTV_objective_1:(i0[10],i1[42])->(o0,o1[1x10,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[1]? arg[1][22] : 0;
    a1=arg[0]? arg[0][0] : 0;
    a2=arg[1]? arg[1][39] : 0;
    a3=(a1-a2);
    a4=casadi_sq(a3);
    a4=(a0*a4);
    a5=arg[0]? arg[0][1] : 0;
    a2=(a5-a2);
    a6=casadi_sq(a2);
    a6=(a0*a6);
    a4=(a4+a6);
    a6=arg[0]? arg[0][2] : 0;
    a7=arg[1]? arg[1][40] : 0;
    a8=(a6-a7);
    a9=casadi_sq(a8);
    a9=(a0*a9);
    a4=(a4+a9);
    a9=arg[0]? arg[0][3] : 0;
    a7=(a9-a7);
    a10=casadi_sq(a7);
    a10=(a0*a10);
    a4=(a4+a10);
    a10=arg[1]? arg[1][23] : 0;
    a11=arg[1]? arg[1][18] : 0;
    a12=2.;
    a11=(a11/a12);
    a12=arg[1]? arg[1][28] : 0;
    a13=arg[1]? arg[1][27] : 0;
    a14=(a12*a13);
    a5=(a14*a5);
    a15=arg[1]? arg[1][17] : 0;
    a5=(a5/a15);
    a16=(a12*a13);
    a1=(a16*a1);
    a1=(a1/a15);
    a5=(a5-a1);
    a1=(a12*a13);
    a6=(a1*a6);
    a6=(a6/a15);
    a5=(a5-a6);
    a12=(a12*a13);
    a9=(a12*a9);
    a9=(a9/a15);
    a5=(a5+a9);
    a5=(a11*a5);
    a9=arg[0]? arg[0][6] : 0;
    a5=(a5-a9);
    a9=casadi_sq(a5);
    a9=(a10*a9);
    a4=(a4+a9);
    a9=arg[1]? arg[1][38] : 0;
    a13=arg[1]? arg[1][25] : 0;
    a13=(a9*a13);
    a6=arg[0]? arg[0][4] : 0;
    a17=casadi_sq(a6);
    a17=(a13*a17);
    a4=(a4+a17);
    a17=arg[1]? arg[1][26] : 0;
    a9=(a9*a17);
    a17=arg[0]? arg[0][5] : 0;
    a18=casadi_sq(a17);
    a18=(a9*a18);
    a4=(a4+a18);
    if (res[0]!=0) res[0][0]=a4;
    a3=(a3+a3);
    a3=(a3*a0);
    a5=(a5+a5);
    a5=(a5*a10);
    a11=(a11*a5);
    a10=(a11/a15);
    a16=(a16*a10);
    a3=(a3-a16);
    if (res[1]!=0) res[1][0]=a3;
    a3=(a11/a15);
    a14=(a14*a3);
    a2=(a2+a2);
    a2=(a2*a0);
    a14=(a14+a2);
    if (res[1]!=0) res[1][1]=a14;
    a8=(a8+a8);
    a8=(a8*a0);
    a14=(a11/a15);
    a1=(a1*a14);
    a8=(a8-a1);
    if (res[1]!=0) res[1][2]=a8;
    a11=(a11/a15);
    a12=(a12*a11);
    a7=(a7+a7);
    a7=(a7*a0);
    a12=(a12+a7);
    if (res[1]!=0) res[1][3]=a12;
    a6=(a6+a6);
    a6=(a6*a13);
    if (res[1]!=0) res[1][4]=a6;
    a17=(a17+a17);
    a17=(a17*a9);
    if (res[1]!=0) res[1][5]=a17;
    a5=(-a5);
    if (res[1]!=0) res[1][6]=a5;
    return 0;
}

int solverTV_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* solverTV_objective_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        case 1: return casadi_s3;
        default: return 0;
    }
}

int solverTV_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_dynamics_1:(i0[10],i1[42])->(o0[4],o1[4x10,15nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[1]? arg[1][18] : 0;
    a1=2.;
    a2=(a0/a1);
    a3=arg[1]? arg[1][28] : 0;
    a4=arg[1]? arg[1][27] : 0;
    a5=(a3*a4);
    a6=arg[0]? arg[0][1] : 0;
    a7=(a5*a6);
    a8=arg[1]? arg[1][17] : 0;
    a7=(a7/a8);
    a9=(a3*a4);
    a10=arg[0]? arg[0][0] : 0;
    a11=(a9*a10);
    a11=(a11/a8);
    a7=(a7-a11);
    a11=(a3*a4);
    a12=arg[0]? arg[0][2] : 0;
    a13=(a11*a12);
    a13=(a13/a8);
    a7=(a7-a13);
    a13=(a3*a4);
    a14=arg[0]? arg[0][3] : 0;
    a15=(a13*a14);
    a15=(a15/a8);
    a7=(a7+a15);
    a7=(a2*a7);
    if (res[0]!=0) res[0][0]=a7;
    a7=arg[0]? arg[0][7] : 0;
    a15=1.0000000000000000e-02;
    a16=arg[1]? arg[1][29] : 0;
    a16=(a15*a16);
    a16=(a7+a16);
    if (res[0]!=0) res[0][1]=a16;
    a16=arg[0]? arg[0][8] : 0;
    a17=arg[1]? arg[1][7] : 0;
    a18=casadi_sq(a17);
    a19=arg[1]? arg[1][16] : 0;
    a18=(a18*a19);
    a20=arg[1]? arg[1][6] : 0;
    a21=casadi_sq(a20);
    a22=arg[1]? arg[1][15] : 0;
    a21=(a21*a22);
    a18=(a18-a21);
    a21=arg[1]? arg[1][8] : 0;
    a23=arg[1]? arg[1][21] : 0;
    a24=(a21*a23);
    a18=(a18/a24);
    a24=(a18*a16);
    a25=casadi_sq(a17);
    a25=(a25*a19);
    a26=casadi_sq(a20);
    a26=(a26*a22);
    a25=(a25-a26);
    a25=(a25/a21);
    a26=arg[0]? arg[0][9] : 0;
    a27=(a25*a26);
    a24=(a24+a27);
    a27=(a0*a3);
    a27=(a27*a4);
    a28=(a1*a21);
    a28=(a28*a8);
    a27=(a27/a28);
    a6=(a27*a6);
    a28=(a0*a3);
    a28=(a28*a4);
    a29=(a1*a21);
    a29=(a29*a8);
    a28=(a28/a29);
    a10=(a28*a10);
    a6=(a6-a10);
    a10=(a0*a3);
    a10=(a10*a4);
    a29=(a1*a21);
    a29=(a29*a8);
    a10=(a10/a29);
    a12=(a10*a12);
    a6=(a6-a12);
    a0=(a0*a3);
    a0=(a0*a4);
    a1=(a1*a21);
    a1=(a1*a8);
    a0=(a0/a1);
    a14=(a0*a14);
    a6=(a6+a14);
    a24=(a24+a6);
    a6=(a20*a22);
    a6=(a6/a21);
    a14=(a6*a7);
    a24=(a24+a14);
    a14=arg[1]? arg[1][9] : 0;
    a1=arg[1]? arg[1][10] : 0;
    a14=(a14+a1);
    a1=arg[1]? arg[1][13] : 0;
    a4=(a22*a1);
    a4=(a14+a4);
    a4=(a20*a4);
    a3=arg[1]? arg[1][11] : 0;
    a12=arg[1]? arg[1][12] : 0;
    a3=(a3+a12);
    a12=arg[1]? arg[1][14] : 0;
    a29=(a19*a12);
    a29=(a3+a29);
    a29=(a17*a29);
    a4=(a4-a29);
    a4=(a4/a21);
    a24=(a24+a4);
    a24=(a15*a24);
    a24=(a16+a24);
    if (res[0]!=0) res[0][2]=a24;
    a17=(a17*a19);
    a20=(a20*a22);
    a17=(a17-a20);
    a20=arg[1]? arg[1][20] : 0;
    a24=casadi_sq(a23);
    a24=(a20*a24);
    a17=(a17/a24);
    a24=1.;
    a17=(a17-a24);
    a16=(a17*a16);
    a4=(a22+a19);
    a21=(a20*a23);
    a4=(a4/a21);
    a21=(a4*a26);
    a16=(a16-a21);
    a21=(a20*a23);
    a21=(a22/a21);
    a7=(a21*a7);
    a16=(a16+a7);
    a22=(a22*a1);
    a14=(a14+a22);
    a14=(a14+a3);
    a19=(a19*a12);
    a14=(a14+a19);
    a20=(a20*a23);
    a14=(a14/a20);
    a16=(a16+a14);
    a16=(a15*a16);
    a26=(a26+a16);
    if (res[0]!=0) res[0][3]=a26;
    a26=(a2/a8);
    a9=(a9*a26);
    a9=(-a9);
    if (res[1]!=0) res[1][0]=a9;
    a9=-1.0000000000000000e-02;
    a28=(a9*a28);
    if (res[1]!=0) res[1][1]=a28;
    a28=(a2/a8);
    a5=(a5*a28);
    if (res[1]!=0) res[1][2]=a5;
    a27=(a15*a27);
    if (res[1]!=0) res[1][3]=a27;
    a27=(a2/a8);
    a11=(a11*a27);
    a11=(-a11);
    if (res[1]!=0) res[1][4]=a11;
    a10=(a9*a10);
    if (res[1]!=0) res[1][5]=a10;
    a2=(a2/a8);
    a13=(a13*a2);
    if (res[1]!=0) res[1][6]=a13;
    a0=(a15*a0);
    if (res[1]!=0) res[1][7]=a0;
    if (res[1]!=0) res[1][8]=a24;
    a6=(a15*a6);
    if (res[1]!=0) res[1][9]=a6;
    a21=(a15*a21);
    if (res[1]!=0) res[1][10]=a21;
    a18=(a15*a18);
    a18=(a24+a18);
    if (res[1]!=0) res[1][11]=a18;
    a17=(a15*a17);
    if (res[1]!=0) res[1][12]=a17;
    a15=(a15*a25);
    if (res[1]!=0) res[1][13]=a15;
    a9=(a9*a4);
    a24=(a24+a9);
    if (res[1]!=0) res[1][14]=a24;
    return 0;
}

int solverTV_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* solverTV_dynamics_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        case 1: return casadi_s5;
        default: return 0;
    }
}

int solverTV_dynamics_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_inequalities_1:(i0[10],i1[42])->(o0[8],o1[8x10,8nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][0] : 0;
    if (res[0]!=0) res[0][0]=a0;
    a1=arg[0]? arg[0][1] : 0;
    if (res[0]!=0) res[0][1]=a1;
    a2=arg[0]? arg[0][2] : 0;
    if (res[0]!=0) res[0][2]=a2;
    a3=arg[0]? arg[0][3] : 0;
    if (res[0]!=0) res[0][3]=a3;
    a4=arg[1]? arg[1][17] : 0;
    a5=arg[1]? arg[1][28] : 0;
    a6=arg[1]? arg[1][27] : 0;
    a7=(a5*a6);
    a7=(a4/a7);
    a8=arg[1]? arg[1][30] : 0;
    a7=(a7*a8);
    a9=arg[1]? arg[1][34] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][10] : 0;
    a11=arg[1]? arg[1][31] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a7=(a7*a9);
    a0=(a0/a7);
    if (res[0]!=0) res[0][4]=a0;
    a0=(a5*a6);
    a0=(a4/a0);
    a0=(a0*a8);
    a9=arg[1]? arg[1][33] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][9] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a0=(a0*a9);
    a1=(a1/a0);
    if (res[0]!=0) res[0][5]=a1;
    a1=(a5*a6);
    a1=(a4/a1);
    a1=(a1*a8);
    a9=arg[1]? arg[1][36] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][12] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a1=(a1*a9);
    a2=(a2/a1);
    if (res[0]!=0) res[0][6]=a2;
    a5=(a5*a6);
    a4=(a4/a5);
    a4=(a4*a8);
    a8=arg[1]? arg[1][35] : 0;
    a8=casadi_sq(a8);
    a5=arg[1]? arg[1][11] : 0;
    a5=(a5/a11);
    a5=casadi_sq(a5);
    a8=(a8-a5);
    a8=sqrt(a8);
    a4=(a4*a8);
    a3=(a3/a4);
    if (res[0]!=0) res[0][7]=a3;
    a3=1.;
    if (res[1]!=0) res[1][0]=a3;
    a7=(1./a7);
    if (res[1]!=0) res[1][1]=a7;
    if (res[1]!=0) res[1][2]=a3;
    a0=(1./a0);
    if (res[1]!=0) res[1][3]=a0;
    if (res[1]!=0) res[1][4]=a3;
    a1=(1./a1);
    if (res[1]!=0) res[1][5]=a1;
    if (res[1]!=0) res[1][6]=a3;
    a4=(1./a4);
    if (res[1]!=0) res[1][7]=a4;
    return 0;
}

int solverTV_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* solverTV_inequalities_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s6;
        case 1: return casadi_s7;
        default: return 0;
    }
}

int solverTV_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_objective_2:(i0[10],i1[42])->(o0,o1[1x10,9nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[1]? arg[1][24] : 0;
    a1=arg[0]? arg[0][8] : 0;
    a2=arg[1]? arg[1][41] : 0;
    a3=arg[1]? arg[1][21] : 0;
    a2=(a2*a3);
    a4=arg[1]? arg[1][19] : 0;
    a5=arg[1]? arg[1][5] : 0;
    a3=casadi_sq(a3);
    a5=(a5*a3);
    a4=(a4+a5);
    a2=(a2/a4);
    a4=arg[0]? arg[0][7] : 0;
    a4=(a2*a4);
    a1=(a1-a4);
    a4=casadi_sq(a1);
    a4=(a0*a4);
    a5=arg[1]? arg[1][22] : 0;
    a3=arg[0]? arg[0][0] : 0;
    a6=arg[1]? arg[1][39] : 0;
    a7=(a3-a6);
    a8=casadi_sq(a7);
    a9=arg[0]? arg[0][1] : 0;
    a6=(a9-a6);
    a10=casadi_sq(a6);
    a8=(a8+a10);
    a10=arg[0]? arg[0][2] : 0;
    a11=arg[1]? arg[1][40] : 0;
    a12=(a10-a11);
    a13=casadi_sq(a12);
    a8=(a8+a13);
    a13=arg[0]? arg[0][3] : 0;
    a11=(a13-a11);
    a14=casadi_sq(a11);
    a8=(a8+a14);
    a8=(a5*a8);
    a4=(a4+a8);
    a8=arg[1]? arg[1][23] : 0;
    a14=arg[1]? arg[1][18] : 0;
    a15=2.;
    a14=(a14/a15);
    a15=arg[1]? arg[1][28] : 0;
    a16=arg[1]? arg[1][27] : 0;
    a17=(a15*a16);
    a9=(a17*a9);
    a18=arg[1]? arg[1][17] : 0;
    a9=(a9/a18);
    a19=(a15*a16);
    a3=(a19*a3);
    a3=(a3/a18);
    a9=(a9-a3);
    a3=(a15*a16);
    a10=(a3*a10);
    a10=(a10/a18);
    a9=(a9-a10);
    a15=(a15*a16);
    a13=(a15*a13);
    a13=(a13/a18);
    a9=(a9+a13);
    a9=(a14*a9);
    a13=arg[0]? arg[0][6] : 0;
    a9=(a9-a13);
    a13=casadi_sq(a9);
    a13=(a8*a13);
    a4=(a4+a13);
    a13=arg[1]? arg[1][38] : 0;
    a16=arg[1]? arg[1][25] : 0;
    a16=(a13*a16);
    a10=arg[0]? arg[0][4] : 0;
    a20=casadi_sq(a10);
    a20=(a16*a20);
    a4=(a4+a20);
    a20=arg[1]? arg[1][26] : 0;
    a13=(a13*a20);
    a20=arg[0]? arg[0][5] : 0;
    a21=casadi_sq(a20);
    a21=(a13*a21);
    a4=(a4+a21);
    if (res[0]!=0) res[0][0]=a4;
    a7=(a7+a7);
    a7=(a7*a5);
    a9=(a9+a9);
    a9=(a9*a8);
    a14=(a14*a9);
    a8=(a14/a18);
    a19=(a19*a8);
    a7=(a7-a19);
    if (res[1]!=0) res[1][0]=a7;
    a7=(a14/a18);
    a17=(a17*a7);
    a6=(a6+a6);
    a6=(a6*a5);
    a17=(a17+a6);
    if (res[1]!=0) res[1][1]=a17;
    a12=(a12+a12);
    a12=(a12*a5);
    a17=(a14/a18);
    a3=(a3*a17);
    a12=(a12-a3);
    if (res[1]!=0) res[1][2]=a12;
    a14=(a14/a18);
    a15=(a15*a14);
    a11=(a11+a11);
    a11=(a11*a5);
    a15=(a15+a11);
    if (res[1]!=0) res[1][3]=a15;
    a10=(a10+a10);
    a10=(a10*a16);
    if (res[1]!=0) res[1][4]=a10;
    a20=(a20+a20);
    a20=(a20*a13);
    if (res[1]!=0) res[1][5]=a20;
    a9=(-a9);
    if (res[1]!=0) res[1][6]=a9;
    a1=(a1+a1);
    a1=(a1*a0);
    a2=(a2*a1);
    a2=(-a2);
    if (res[1]!=0) res[1][7]=a2;
    if (res[1]!=0) res[1][8]=a1;
    return 0;
}

int solverTV_objective_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f3(arg, res, iw, w, mem);
}

const casadi_int* solverTV_objective_2_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        case 1: return casadi_s8;
        default: return 0;
    }
}

int solverTV_objective_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_dynamics_2:(i0[10],i1[42])->(o0[4],o1[4x10,15nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[1]? arg[1][18] : 0;
    a1=2.;
    a2=(a0/a1);
    a3=arg[1]? arg[1][28] : 0;
    a4=arg[1]? arg[1][27] : 0;
    a5=(a3*a4);
    a6=arg[0]? arg[0][1] : 0;
    a7=(a5*a6);
    a8=arg[1]? arg[1][17] : 0;
    a7=(a7/a8);
    a9=(a3*a4);
    a10=arg[0]? arg[0][0] : 0;
    a11=(a9*a10);
    a11=(a11/a8);
    a7=(a7-a11);
    a11=(a3*a4);
    a12=arg[0]? arg[0][2] : 0;
    a13=(a11*a12);
    a13=(a13/a8);
    a7=(a7-a13);
    a13=(a3*a4);
    a14=arg[0]? arg[0][3] : 0;
    a15=(a13*a14);
    a15=(a15/a8);
    a7=(a7+a15);
    a7=(a2*a7);
    if (res[0]!=0) res[0][0]=a7;
    a7=arg[0]? arg[0][7] : 0;
    a15=1.0000000000000000e-02;
    a16=arg[1]? arg[1][29] : 0;
    a16=(a15*a16);
    a16=(a7+a16);
    if (res[0]!=0) res[0][1]=a16;
    a16=arg[0]? arg[0][8] : 0;
    a17=arg[1]? arg[1][7] : 0;
    a18=casadi_sq(a17);
    a19=arg[1]? arg[1][16] : 0;
    a18=(a18*a19);
    a20=arg[1]? arg[1][6] : 0;
    a21=casadi_sq(a20);
    a22=arg[1]? arg[1][15] : 0;
    a21=(a21*a22);
    a18=(a18-a21);
    a21=arg[1]? arg[1][8] : 0;
    a23=arg[1]? arg[1][21] : 0;
    a24=(a21*a23);
    a18=(a18/a24);
    a24=(a18*a16);
    a25=casadi_sq(a17);
    a25=(a25*a19);
    a26=casadi_sq(a20);
    a26=(a26*a22);
    a25=(a25-a26);
    a25=(a25/a21);
    a26=arg[0]? arg[0][9] : 0;
    a27=(a25*a26);
    a24=(a24+a27);
    a27=(a0*a3);
    a27=(a27*a4);
    a28=(a1*a21);
    a28=(a28*a8);
    a27=(a27/a28);
    a6=(a27*a6);
    a28=(a0*a3);
    a28=(a28*a4);
    a29=(a1*a21);
    a29=(a29*a8);
    a28=(a28/a29);
    a10=(a28*a10);
    a6=(a6-a10);
    a10=(a0*a3);
    a10=(a10*a4);
    a29=(a1*a21);
    a29=(a29*a8);
    a10=(a10/a29);
    a12=(a10*a12);
    a6=(a6-a12);
    a0=(a0*a3);
    a0=(a0*a4);
    a1=(a1*a21);
    a1=(a1*a8);
    a0=(a0/a1);
    a14=(a0*a14);
    a6=(a6+a14);
    a24=(a24+a6);
    a6=(a20*a22);
    a6=(a6/a21);
    a14=(a6*a7);
    a24=(a24+a14);
    a14=arg[1]? arg[1][9] : 0;
    a1=arg[1]? arg[1][10] : 0;
    a14=(a14+a1);
    a1=arg[1]? arg[1][13] : 0;
    a4=(a22*a1);
    a4=(a14+a4);
    a4=(a20*a4);
    a3=arg[1]? arg[1][11] : 0;
    a12=arg[1]? arg[1][12] : 0;
    a3=(a3+a12);
    a12=arg[1]? arg[1][14] : 0;
    a29=(a19*a12);
    a29=(a3+a29);
    a29=(a17*a29);
    a4=(a4-a29);
    a4=(a4/a21);
    a24=(a24+a4);
    a24=(a15*a24);
    a24=(a16+a24);
    if (res[0]!=0) res[0][2]=a24;
    a17=(a17*a19);
    a20=(a20*a22);
    a17=(a17-a20);
    a20=arg[1]? arg[1][20] : 0;
    a24=casadi_sq(a23);
    a24=(a20*a24);
    a17=(a17/a24);
    a24=1.;
    a17=(a17-a24);
    a16=(a17*a16);
    a4=(a22+a19);
    a21=(a20*a23);
    a4=(a4/a21);
    a21=(a4*a26);
    a16=(a16-a21);
    a21=(a20*a23);
    a21=(a22/a21);
    a7=(a21*a7);
    a16=(a16+a7);
    a22=(a22*a1);
    a14=(a14+a22);
    a14=(a14+a3);
    a19=(a19*a12);
    a14=(a14+a19);
    a20=(a20*a23);
    a14=(a14/a20);
    a16=(a16+a14);
    a16=(a15*a16);
    a26=(a26+a16);
    if (res[0]!=0) res[0][3]=a26;
    a26=(a2/a8);
    a9=(a9*a26);
    a9=(-a9);
    if (res[1]!=0) res[1][0]=a9;
    a9=-1.0000000000000000e-02;
    a28=(a9*a28);
    if (res[1]!=0) res[1][1]=a28;
    a28=(a2/a8);
    a5=(a5*a28);
    if (res[1]!=0) res[1][2]=a5;
    a27=(a15*a27);
    if (res[1]!=0) res[1][3]=a27;
    a27=(a2/a8);
    a11=(a11*a27);
    a11=(-a11);
    if (res[1]!=0) res[1][4]=a11;
    a10=(a9*a10);
    if (res[1]!=0) res[1][5]=a10;
    a2=(a2/a8);
    a13=(a13*a2);
    if (res[1]!=0) res[1][6]=a13;
    a0=(a15*a0);
    if (res[1]!=0) res[1][7]=a0;
    if (res[1]!=0) res[1][8]=a24;
    a6=(a15*a6);
    if (res[1]!=0) res[1][9]=a6;
    a21=(a15*a21);
    if (res[1]!=0) res[1][10]=a21;
    a18=(a15*a18);
    a18=(a24+a18);
    if (res[1]!=0) res[1][11]=a18;
    a17=(a15*a17);
    if (res[1]!=0) res[1][12]=a17;
    a15=(a15*a25);
    if (res[1]!=0) res[1][13]=a15;
    a9=(a9*a4);
    a24=(a24+a9);
    if (res[1]!=0) res[1][14]=a24;
    return 0;
}

int solverTV_dynamics_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f4(arg, res, iw, w, mem);
}

const casadi_int* solverTV_dynamics_2_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        case 1: return casadi_s5;
        default: return 0;
    }
}

int solverTV_dynamics_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_inequalities_2:(i0[10],i1[42])->(o0[10],o1[10x10,13nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][0] : 0;
    if (res[0]!=0) res[0][0]=a0;
    a1=arg[0]? arg[0][1] : 0;
    if (res[0]!=0) res[0][1]=a1;
    a2=arg[0]? arg[0][2] : 0;
    if (res[0]!=0) res[0][2]=a2;
    a3=arg[0]? arg[0][3] : 0;
    if (res[0]!=0) res[0][3]=a3;
    a4=arg[1]? arg[1][17] : 0;
    a5=arg[1]? arg[1][28] : 0;
    a6=arg[1]? arg[1][27] : 0;
    a7=(a5*a6);
    a7=(a4/a7);
    a8=arg[1]? arg[1][30] : 0;
    a7=(a7*a8);
    a9=arg[1]? arg[1][34] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][10] : 0;
    a11=arg[1]? arg[1][31] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a7=(a7*a9);
    a0=(a0/a7);
    if (res[0]!=0) res[0][4]=a0;
    a0=(a5*a6);
    a0=(a4/a0);
    a0=(a0*a8);
    a9=arg[1]? arg[1][33] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][9] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a0=(a0*a9);
    a1=(a1/a0);
    if (res[0]!=0) res[0][5]=a1;
    a1=(a5*a6);
    a1=(a4/a1);
    a1=(a1*a8);
    a9=arg[1]? arg[1][36] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][12] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a1=(a1*a9);
    a2=(a2/a1);
    if (res[0]!=0) res[0][6]=a2;
    a5=(a5*a6);
    a4=(a4/a5);
    a4=(a4*a8);
    a8=arg[1]? arg[1][35] : 0;
    a8=casadi_sq(a8);
    a5=arg[1]? arg[1][11] : 0;
    a5=(a5/a11);
    a5=casadi_sq(a5);
    a8=(a8-a5);
    a8=sqrt(a8);
    a4=(a4*a8);
    a3=(a3/a4);
    if (res[0]!=0) res[0][7]=a3;
    a3=arg[0]? arg[0][8] : 0;
    a8=arg[0]? arg[0][4] : 0;
    a8=(a3-a8);
    a5=arg[1]? arg[1][37] : 0;
    a11=(a11*a5);
    a5=arg[1]? arg[1][21] : 0;
    a11=(a11/a5);
    a8=(a8/a11);
    if (res[0]!=0) res[0][8]=a8;
    a8=arg[0]? arg[0][9] : 0;
    a6=arg[1]? arg[1][7] : 0;
    a3=(a6*a3);
    a3=(a3/a5);
    a8=(a8-a3);
    a3=arg[0]? arg[0][5] : 0;
    a8=(a8-a3);
    a3=arg[1]? arg[1][32] : 0;
    a8=(a8/a3);
    if (res[0]!=0) res[0][9]=a8;
    a8=1.;
    if (res[1]!=0) res[1][0]=a8;
    a7=(1./a7);
    if (res[1]!=0) res[1][1]=a7;
    if (res[1]!=0) res[1][2]=a8;
    a0=(1./a0);
    if (res[1]!=0) res[1][3]=a0;
    if (res[1]!=0) res[1][4]=a8;
    a1=(1./a1);
    if (res[1]!=0) res[1][5]=a1;
    if (res[1]!=0) res[1][6]=a8;
    a4=(1./a4);
    if (res[1]!=0) res[1][7]=a4;
    a11=(1./a11);
    a4=(-a11);
    if (res[1]!=0) res[1][8]=a4;
    a4=(1./a3);
    a8=(-a4);
    if (res[1]!=0) res[1][9]=a8;
    if (res[1]!=0) res[1][10]=a11;
    a6=(a6/a5);
    a6=(a6/a3);
    a6=(-a6);
    if (res[1]!=0) res[1][11]=a6;
    if (res[1]!=0) res[1][12]=a4;
    return 0;
}

int solverTV_inequalities_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f5(arg, res, iw, w, mem);
}

const casadi_int* solverTV_inequalities_2_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s9;
        default: return 0;
    }
}

int solverTV_inequalities_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_objective_14:(i0[10],i1[42])->(o0,o1[1x10,9nz]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[1]? arg[1][24] : 0;
    a1=arg[0]? arg[0][8] : 0;
    a2=arg[1]? arg[1][41] : 0;
    a3=arg[1]? arg[1][21] : 0;
    a2=(a2*a3);
    a4=arg[1]? arg[1][19] : 0;
    a5=arg[1]? arg[1][5] : 0;
    a3=casadi_sq(a3);
    a5=(a5*a3);
    a4=(a4+a5);
    a2=(a2/a4);
    a4=arg[0]? arg[0][7] : 0;
    a4=(a2*a4);
    a1=(a1-a4);
    a4=casadi_sq(a1);
    a4=(a0*a4);
    a5=arg[1]? arg[1][22] : 0;
    a3=arg[0]? arg[0][0] : 0;
    a6=arg[1]? arg[1][39] : 0;
    a7=(a3-a6);
    a8=casadi_sq(a7);
    a9=arg[0]? arg[0][1] : 0;
    a6=(a9-a6);
    a10=casadi_sq(a6);
    a8=(a8+a10);
    a10=arg[0]? arg[0][2] : 0;
    a11=arg[1]? arg[1][40] : 0;
    a12=(a10-a11);
    a13=casadi_sq(a12);
    a8=(a8+a13);
    a13=arg[0]? arg[0][3] : 0;
    a11=(a13-a11);
    a14=casadi_sq(a11);
    a8=(a8+a14);
    a8=(a5*a8);
    a4=(a4+a8);
    a8=arg[1]? arg[1][23] : 0;
    a14=arg[1]? arg[1][18] : 0;
    a15=2.;
    a14=(a14/a15);
    a15=arg[1]? arg[1][28] : 0;
    a16=arg[1]? arg[1][27] : 0;
    a17=(a15*a16);
    a9=(a17*a9);
    a18=arg[1]? arg[1][17] : 0;
    a9=(a9/a18);
    a19=(a15*a16);
    a3=(a19*a3);
    a3=(a3/a18);
    a9=(a9-a3);
    a3=(a15*a16);
    a10=(a3*a10);
    a10=(a10/a18);
    a9=(a9-a10);
    a15=(a15*a16);
    a13=(a15*a13);
    a13=(a13/a18);
    a9=(a9+a13);
    a9=(a14*a9);
    a13=arg[0]? arg[0][6] : 0;
    a9=(a9-a13);
    a13=casadi_sq(a9);
    a13=(a8*a13);
    a4=(a4+a13);
    a13=arg[1]? arg[1][38] : 0;
    a16=arg[1]? arg[1][25] : 0;
    a16=(a13*a16);
    a10=arg[0]? arg[0][4] : 0;
    a20=casadi_sq(a10);
    a20=(a16*a20);
    a4=(a4+a20);
    a20=arg[1]? arg[1][26] : 0;
    a13=(a13*a20);
    a20=arg[0]? arg[0][5] : 0;
    a21=casadi_sq(a20);
    a21=(a13*a21);
    a4=(a4+a21);
    if (res[0]!=0) res[0][0]=a4;
    a7=(a7+a7);
    a7=(a7*a5);
    a9=(a9+a9);
    a9=(a9*a8);
    a14=(a14*a9);
    a8=(a14/a18);
    a19=(a19*a8);
    a7=(a7-a19);
    if (res[1]!=0) res[1][0]=a7;
    a7=(a14/a18);
    a17=(a17*a7);
    a6=(a6+a6);
    a6=(a6*a5);
    a17=(a17+a6);
    if (res[1]!=0) res[1][1]=a17;
    a12=(a12+a12);
    a12=(a12*a5);
    a17=(a14/a18);
    a3=(a3*a17);
    a12=(a12-a3);
    if (res[1]!=0) res[1][2]=a12;
    a14=(a14/a18);
    a15=(a15*a14);
    a11=(a11+a11);
    a11=(a11*a5);
    a15=(a15+a11);
    if (res[1]!=0) res[1][3]=a15;
    a10=(a10+a10);
    a10=(a10*a16);
    if (res[1]!=0) res[1][4]=a10;
    a20=(a20+a20);
    a20=(a20*a13);
    if (res[1]!=0) res[1][5]=a20;
    a9=(-a9);
    if (res[1]!=0) res[1][6]=a9;
    a1=(a1+a1);
    a1=(a1*a0);
    a2=(a2*a1);
    a2=(-a2);
    if (res[1]!=0) res[1][7]=a2;
    if (res[1]!=0) res[1][8]=a1;
    return 0;
}

int solverTV_objective_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f6(arg, res, iw, w, mem);
}

const casadi_int* solverTV_objective_14_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        case 1: return casadi_s8;
        default: return 0;
    }
}

int solverTV_objective_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_dynamics_14:(i0[10],i1[42])->(o0[3],o1[3x10,11nz]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][7] : 0;
    a1=1.0000000000000000e-02;
    a2=arg[1]? arg[1][29] : 0;
    a2=(a1*a2);
    a2=(a0+a2);
    if (res[0]!=0) res[0][0]=a2;
    a2=arg[0]? arg[0][8] : 0;
    a3=arg[1]? arg[1][7] : 0;
    a4=casadi_sq(a3);
    a5=arg[1]? arg[1][16] : 0;
    a4=(a4*a5);
    a6=arg[1]? arg[1][6] : 0;
    a7=casadi_sq(a6);
    a8=arg[1]? arg[1][15] : 0;
    a7=(a7*a8);
    a4=(a4-a7);
    a7=arg[1]? arg[1][8] : 0;
    a9=arg[1]? arg[1][21] : 0;
    a10=(a7*a9);
    a4=(a4/a10);
    a10=(a4*a2);
    a11=casadi_sq(a3);
    a11=(a11*a5);
    a12=casadi_sq(a6);
    a12=(a12*a8);
    a11=(a11-a12);
    a11=(a11/a7);
    a12=arg[0]? arg[0][9] : 0;
    a13=(a11*a12);
    a10=(a10+a13);
    a13=arg[1]? arg[1][18] : 0;
    a14=arg[1]? arg[1][28] : 0;
    a15=(a13*a14);
    a16=arg[1]? arg[1][27] : 0;
    a15=(a15*a16);
    a17=2.;
    a18=(a17*a7);
    a19=arg[1]? arg[1][17] : 0;
    a18=(a18*a19);
    a15=(a15/a18);
    a18=arg[0]? arg[0][1] : 0;
    a18=(a15*a18);
    a20=(a13*a14);
    a20=(a20*a16);
    a21=(a17*a7);
    a21=(a21*a19);
    a20=(a20/a21);
    a21=arg[0]? arg[0][0] : 0;
    a21=(a20*a21);
    a18=(a18-a21);
    a21=(a13*a14);
    a21=(a21*a16);
    a22=(a17*a7);
    a22=(a22*a19);
    a21=(a21/a22);
    a22=arg[0]? arg[0][2] : 0;
    a22=(a21*a22);
    a18=(a18-a22);
    a13=(a13*a14);
    a13=(a13*a16);
    a17=(a17*a7);
    a17=(a17*a19);
    a13=(a13/a17);
    a17=arg[0]? arg[0][3] : 0;
    a17=(a13*a17);
    a18=(a18+a17);
    a10=(a10+a18);
    a18=(a6*a8);
    a18=(a18/a7);
    a17=(a18*a0);
    a10=(a10+a17);
    a17=arg[1]? arg[1][9] : 0;
    a19=arg[1]? arg[1][10] : 0;
    a17=(a17+a19);
    a19=arg[1]? arg[1][13] : 0;
    a16=(a8*a19);
    a16=(a17+a16);
    a16=(a6*a16);
    a14=arg[1]? arg[1][11] : 0;
    a22=arg[1]? arg[1][12] : 0;
    a14=(a14+a22);
    a22=arg[1]? arg[1][14] : 0;
    a23=(a5*a22);
    a23=(a14+a23);
    a23=(a3*a23);
    a16=(a16-a23);
    a16=(a16/a7);
    a10=(a10+a16);
    a10=(a1*a10);
    a10=(a2+a10);
    if (res[0]!=0) res[0][1]=a10;
    a3=(a3*a5);
    a6=(a6*a8);
    a3=(a3-a6);
    a6=arg[1]? arg[1][20] : 0;
    a10=casadi_sq(a9);
    a10=(a6*a10);
    a3=(a3/a10);
    a10=1.;
    a3=(a3-a10);
    a2=(a3*a2);
    a16=(a8+a5);
    a7=(a6*a9);
    a16=(a16/a7);
    a7=(a16*a12);
    a2=(a2-a7);
    a7=(a6*a9);
    a7=(a8/a7);
    a0=(a7*a0);
    a2=(a2+a0);
    a8=(a8*a19);
    a17=(a17+a8);
    a17=(a17+a14);
    a5=(a5*a22);
    a17=(a17+a5);
    a6=(a6*a9);
    a17=(a17/a6);
    a2=(a2+a17);
    a2=(a1*a2);
    a12=(a12+a2);
    if (res[0]!=0) res[0][2]=a12;
    a12=-1.0000000000000000e-02;
    a20=(a12*a20);
    if (res[1]!=0) res[1][0]=a20;
    a15=(a1*a15);
    if (res[1]!=0) res[1][1]=a15;
    a21=(a12*a21);
    if (res[1]!=0) res[1][2]=a21;
    a13=(a1*a13);
    if (res[1]!=0) res[1][3]=a13;
    if (res[1]!=0) res[1][4]=a10;
    a18=(a1*a18);
    if (res[1]!=0) res[1][5]=a18;
    a7=(a1*a7);
    if (res[1]!=0) res[1][6]=a7;
    a4=(a1*a4);
    a4=(a10+a4);
    if (res[1]!=0) res[1][7]=a4;
    a3=(a1*a3);
    if (res[1]!=0) res[1][8]=a3;
    a1=(a1*a11);
    if (res[1]!=0) res[1][9]=a1;
    a12=(a12*a16);
    a10=(a10+a12);
    if (res[1]!=0) res[1][10]=a10;
    return 0;
}

int solverTV_dynamics_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f7(arg, res, iw, w, mem);
}

const casadi_int* solverTV_dynamics_14_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s10;
        case 1: return casadi_s11;
        default: return 0;
    }
}

int solverTV_dynamics_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_inequalities_14:(i0[10],i1[42])->(o0[10],o1[10x10,13nz]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][0] : 0;
    if (res[0]!=0) res[0][0]=a0;
    a1=arg[0]? arg[0][1] : 0;
    if (res[0]!=0) res[0][1]=a1;
    a2=arg[0]? arg[0][2] : 0;
    if (res[0]!=0) res[0][2]=a2;
    a3=arg[0]? arg[0][3] : 0;
    if (res[0]!=0) res[0][3]=a3;
    a4=arg[1]? arg[1][17] : 0;
    a5=arg[1]? arg[1][28] : 0;
    a6=arg[1]? arg[1][27] : 0;
    a7=(a5*a6);
    a7=(a4/a7);
    a8=arg[1]? arg[1][30] : 0;
    a7=(a7*a8);
    a9=arg[1]? arg[1][34] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][10] : 0;
    a11=arg[1]? arg[1][31] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a7=(a7*a9);
    a0=(a0/a7);
    if (res[0]!=0) res[0][4]=a0;
    a0=(a5*a6);
    a0=(a4/a0);
    a0=(a0*a8);
    a9=arg[1]? arg[1][33] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][9] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a0=(a0*a9);
    a1=(a1/a0);
    if (res[0]!=0) res[0][5]=a1;
    a1=(a5*a6);
    a1=(a4/a1);
    a1=(a1*a8);
    a9=arg[1]? arg[1][36] : 0;
    a9=casadi_sq(a9);
    a10=arg[1]? arg[1][12] : 0;
    a10=(a10/a11);
    a10=casadi_sq(a10);
    a9=(a9-a10);
    a9=sqrt(a9);
    a1=(a1*a9);
    a2=(a2/a1);
    if (res[0]!=0) res[0][6]=a2;
    a5=(a5*a6);
    a4=(a4/a5);
    a4=(a4*a8);
    a8=arg[1]? arg[1][35] : 0;
    a8=casadi_sq(a8);
    a5=arg[1]? arg[1][11] : 0;
    a5=(a5/a11);
    a5=casadi_sq(a5);
    a8=(a8-a5);
    a8=sqrt(a8);
    a4=(a4*a8);
    a3=(a3/a4);
    if (res[0]!=0) res[0][7]=a3;
    a3=arg[0]? arg[0][8] : 0;
    a8=arg[0]? arg[0][4] : 0;
    a8=(a3-a8);
    a5=arg[1]? arg[1][37] : 0;
    a11=(a11*a5);
    a5=arg[1]? arg[1][21] : 0;
    a11=(a11/a5);
    a8=(a8/a11);
    if (res[0]!=0) res[0][8]=a8;
    a8=arg[0]? arg[0][9] : 0;
    a6=arg[1]? arg[1][7] : 0;
    a3=(a6*a3);
    a3=(a3/a5);
    a8=(a8-a3);
    a3=arg[0]? arg[0][5] : 0;
    a8=(a8-a3);
    a3=arg[1]? arg[1][32] : 0;
    a8=(a8/a3);
    if (res[0]!=0) res[0][9]=a8;
    a8=1.;
    if (res[1]!=0) res[1][0]=a8;
    a7=(1./a7);
    if (res[1]!=0) res[1][1]=a7;
    if (res[1]!=0) res[1][2]=a8;
    a0=(1./a0);
    if (res[1]!=0) res[1][3]=a0;
    if (res[1]!=0) res[1][4]=a8;
    a1=(1./a1);
    if (res[1]!=0) res[1][5]=a1;
    if (res[1]!=0) res[1][6]=a8;
    a4=(1./a4);
    if (res[1]!=0) res[1][7]=a4;
    a11=(1./a11);
    a4=(-a11);
    if (res[1]!=0) res[1][8]=a4;
    a4=(1./a3);
    a8=(-a4);
    if (res[1]!=0) res[1][9]=a8;
    if (res[1]!=0) res[1][10]=a11;
    a6=(a6/a5);
    a6=(a6/a3);
    a6=(-a6);
    if (res[1]!=0) res[1][11]=a6;
    if (res[1]!=0) res[1][12]=a4;
    return 0;
}

int solverTV_inequalities_14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f8(arg, res, iw, w, mem);
}

const casadi_int* solverTV_inequalities_14_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s9;
        default: return 0;
    }
}

int solverTV_inequalities_14_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_objective_15:(i0[5],i1[42])->(o0,o1[1x5,4nz]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=arg[1]? arg[1][24] : 0;
    a1=arg[0]? arg[0][3] : 0;
    a2=arg[1]? arg[1][41] : 0;
    a3=arg[1]? arg[1][21] : 0;
    a2=(a2*a3);
    a4=arg[1]? arg[1][19] : 0;
    a5=arg[1]? arg[1][5] : 0;
    a3=casadi_sq(a3);
    a5=(a5*a3);
    a4=(a4+a5);
    a2=(a2/a4);
    a4=arg[0]? arg[0][2] : 0;
    a4=(a2*a4);
    a1=(a1-a4);
    a4=casadi_sq(a1);
    a4=(a0*a4);
    a5=arg[1]? arg[1][38] : 0;
    a3=arg[1]? arg[1][25] : 0;
    a3=(a5*a3);
    a6=arg[0]? arg[0][0] : 0;
    a7=casadi_sq(a6);
    a7=(a3*a7);
    a4=(a4+a7);
    a7=arg[1]? arg[1][26] : 0;
    a5=(a5*a7);
    a7=arg[0]? arg[0][1] : 0;
    a8=casadi_sq(a7);
    a8=(a5*a8);
    a4=(a4+a8);
    if (res[0]!=0) res[0][0]=a4;
    a6=(a6+a6);
    a6=(a6*a3);
    if (res[1]!=0) res[1][0]=a6;
    a7=(a7+a7);
    a7=(a7*a5);
    if (res[1]!=0) res[1][1]=a7;
    a1=(a1+a1);
    a1=(a1*a0);
    a2=(a2*a1);
    a2=(-a2);
    if (res[1]!=0) res[1][2]=a2;
    if (res[1]!=0) res[1][3]=a1;
    return 0;
}

int solverTV_objective_15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f9(arg, res, iw, w, mem);
}

const casadi_int* solverTV_objective_15_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s2;
        case 1: return casadi_s13;
        default: return 0;
    }
}

int solverTV_objective_15_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

/* solverTV_inequalities_15:(i0[5],i1[42])->(o0[2],o1[2x5,5nz]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=arg[0]? arg[0][3] : 0;
    a1=arg[0]? arg[0][0] : 0;
    a1=(a0-a1);
    a2=arg[1]? arg[1][31] : 0;
    a3=arg[1]? arg[1][37] : 0;
    a2=(a2*a3);
    a3=arg[1]? arg[1][21] : 0;
    a2=(a2/a3);
    a1=(a1/a2);
    if (res[0]!=0) res[0][0]=a1;
    a1=arg[0]? arg[0][4] : 0;
    a4=arg[1]? arg[1][7] : 0;
    a0=(a4*a0);
    a0=(a0/a3);
    a1=(a1-a0);
    a0=arg[0]? arg[0][1] : 0;
    a1=(a1-a0);
    a0=arg[1]? arg[1][32] : 0;
    a1=(a1/a0);
    if (res[0]!=0) res[0][1]=a1;
    a2=(1./a2);
    a1=(-a2);
    if (res[1]!=0) res[1][0]=a1;
    a1=(1./a0);
    a5=(-a1);
    if (res[1]!=0) res[1][1]=a5;
    if (res[1]!=0) res[1][2]=a2;
    a4=(a4/a3);
    a4=(a4/a0);
    a4=(-a4);
    if (res[1]!=0) res[1][3]=a4;
    if (res[1]!=0) res[1][4]=a1;
    return 0;
}

int solverTV_inequalities_15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f10(arg, res, iw, w, mem);
}

const casadi_int* solverTV_inequalities_15_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s14;
        case 1: return casadi_s15;
        default: return 0;
    }
}

int solverTV_inequalities_15_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 2;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
